### ISSUE TITLE
DOCUMENTATION links are wrong

### ISSUE THREAD

**Issue by smirnov-mi** [rancher/rancher-docs#1034]
Links to documentation on e.g. this page:
https://github.com/rancher/rancher/blob/release/v2.8/README.md
are pointing to e.g. https://rancher.com/docs/rancher/v2.8/en/installation/

whereas I was only able to find the real documentation under

https://ranchermanager.docs.rancher.com/v2.8/pages-for-subheaders/installation-and-upgrade

Not sure if the links must be fixed or the documentation path of the real pages.

**Comment by martyav** [comment]
Not sure why this was transferred, as it pertains to a page in rancher/rancher...

**Comment by martyav** [comment]
Imo this issue shouldn't have been transferred since it relates to the rancher/rancher readme having a broken link
