### ISSUE TITLE
Support matrix v2.8.0 link wrong (redirect to support matrix v.2.7.9)

### ISSUE THREAD

**Issue by welkson** [rancher/rancher-docs#1046]
Documentation:
https://ranchermanager.docs.rancher.com/versions

Click on "Support Matrix" (v2.8.0) and will redirect to Support Matrix v.2.7.9 page.

**Comment by martyav** [comment]
Thanks for letting us know. The support matrix site is maintained by another team and we'll have to wait until they add a page for v2.8.0

**Comment by martyav** [comment]
@welkson As it turns out, the link has been removed, as v2.8.0 was an unstable release. Users running v2.8.0 are recommended to upgrade to the latest stable Rancher release -- in this case, v2.8.1. See the [v2.8.1 release notes](https://github.com/rancher/rancher/releases/tag/v2.8.1).
