### ISSUE TITLE
The "Launching Kubernetes on Windows Clusters" documentation should be revamped

### ISSUE THREAD

**Issue by kourosh7** [rancher/rancher-docs#1074]
## Summary

The [Launching Kubernetes on Windows Clusters](https://ranchermanager.docs.rancher.com/pages-for-subheaders/use-windows-clusters) documentation should be revamped. It seems to have outdated info that was leftover from provisioning RKE1 Windows clusters which is now [EOL](https://www.suse.com/support/kb/doc/?id=000020684). 

Here are some items that I noticed are outdated/incorrect after provisioning a supported WIndows RKE2 cluster through Rancher:

1. The first section on the page mentions RKE but it should be RKE2 since RKE1 Windows Clusters are EOL.
2. The first section says, `You can only add Windows nodes to a cluster if Windows support is enabled when the cluster is created. Windows support cannot be enabled for existing clusters.` However, this is no longer the case on Windows RKE2 clusters.
3. The first section says, `Kubernetes 1.15+ is required.` This should be updated to a supported K8s version
4. The next session is titled: [OS and Docker Requirements](https://ranchermanager.docs.rancher.com/pages-for-subheaders/use-windows-clusters#os-and-docker-requirements) but Docker is not used in RKE2
5. The [Networking Requirements](https://ranchermanager.docs.rancher.com/pages-for-subheaders/use-windows-clusters#networking-requirements) section says `Rancher only supports Windows using Flannel as the network provider.` But it is actually `calico` in RKE2
6. The [Tutorial: How to Create a Cluster with Windows Support](https://ranchermanager.docs.rancher.com/pages-for-subheaders/use-windows-clusters#tutorial-how-to-create-a-cluster-with-windows-support) says `When you create or edit your cluster from the Rancher UI, you will see a Customize Node Run Command that you can run on each server to add it to your cluster.` That has changed to the `Registration Command`
7. In section [2. Create the Cluster on Existing Nodes](https://ranchermanager.docs.rancher.com/pages-for-subheaders/use-windows-clusters#2-create-the-cluster-on-existing-nodes), steps 5,6,7,8 are incorrect and should mention a supported K8s version, `Calico` instead of `Flannel`, and there is no longer an extra option to enable `Windows Support` or choose a `Flannel Backend` 
8. Section [3. Add Nodes to the Cluster](https://ranchermanager.docs.rancher.com/pages-for-subheaders/use-windows-clusters#3-add-nodes-to-the-cluster) should be updated for all three subsections (Add Linux Master Node, Add Linux Worker Node, Add Windows Worker Node). Once the cluster is created from the `Cluster Configuration` page, you will then have a `Registration` section which will allow you to select `Node Roles` in the `Step 1` section. Then the `Step 2` section will have the `Registration Command` you run on the nodes. The registration command for the `Windows` node will become available when the cluster has working Linux nodes with `etcd`, `control plane`, and `worker` roles active.

**Comment by btat** [comment]
Possibly related to https://github.com/rancher/rancher-docs/issues/997

**Comment by sunilarjun** [comment]
Hello @kourosh7! I had some questions regarding the page refresh with respect to RKE2:

1. In the [Kubernetes Version](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/use-windows-clusters#kubernetes-version) section where it states information on v1.15+/v1.21 K8s requirements, are these still needed here or can they be replaced with the support matrix for RKE2 for relevant Kubernetes version info?
2. Are these descriptions about the [two network options](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/use-windows-clusters#kubernetes-version:~:text=the%20network%20provider.-,There%20are%20two%20network%20options%3A%20Host%20Gateway%20(L2bridge)%20and%20VXLAN%20(Overlay).%20The%20default%20option%20is%20VXLAN%20(Overlay)%20mode.,-For%20Host%20Gateway) relevant here or are they more RKE1 material that can be removed?

Any guidance much appreciated, thank you!

**Comment by kourosh7** [comment]
Hi @sunilarjun, sorry for the late reply.

1. Not needed, I think it would be best to point to the support matrix
2. Also not needed, those options link to flannel docs, and for rke2 we use calico

**Comment by kourosh7** [comment]
For reference, you can see this RKE2 custom cluster created in Rancher using the flannel CNI no longer gives you an option to register a Windows node:
![image](https://github.com/rancher/rancher-docs/assets/39573922/1fd3bffe-12bd-42ed-b9c0-c6d6a230ca87)
![image](https://github.com/rancher/rancher-docs/assets/39573922/60e09725-684b-422e-a3e9-b7324f7b5c2a)

Whereas, in this RKE2 custom cluster created in Rancher where calico is the CNI, you can clearly see an option to register a Windows node:
![image](https://github.com/rancher/rancher-docs/assets/39573922/42c6755f-fdca-43bb-8694-ea22b250e37c)

**Comment by sunilarjun** [comment]
@kourosh7 Thank you for the response! I've adjusted my PR accordingly with the clarifications.
