### ISSUE TITLE
Clear up confusing API documentation

### ISSUE THREAD

**Issue by cbron** [rancher/rancher-docs#1089]
## Summary

This page is now out of date: https://ranchermanager.docs.rancher.com/reference-guides/about-the-api
It refers to "The API", but the official API is now: https://ranchermanager.docs.rancher.com/v2.8/api/quickstart
I believe the best option would be to move the first link into a secondary section of second link, where it's referred to as the previous api. Or something along those lines.

**Comment by martyav** [comment]
@cbron Some of the content in our docs points to pages describing how token generation works in the previous API. For example, on https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-references/feature-flags:

> `token-hashing`: Enables token hashing. Once enabled, existing tokens will be hashed and all new tokens will be hashed automatically with the SHA256 algorithm. Once a token is hashed it can't be undone. This flag can't be disabled after its enabled. See [API Tokens](https://ranchermanager.docs.rancher.com/reference-guides/about-the-api/api-tokens#token-hashing) for more information.

Does the content on [API Tokens](https://ranchermanager.docs.rancher.com/reference-guides/about-the-api/api-tokens) still apply to RK-API?
