### ISSUE TITLE
Replace 2 separate cloud FAQs with a single unified version

### ISSUE THREAD

**Issue by stephenmogg** [rancher/rancher-docs#1113]
There are currently 2 versions of the Rancher PAYG FAQ.
One for Azure, One for AWS.

https://github.com/rancher/rancher-docs/blob/main/versioned_docs/version-2.7/integrations-in-rancher/cloud-marketplace/aws-marketplace-payg-integration/aws-marketplace-payg-integration.md

https://github.com/rancher/rancher-docs/blob/main/versioned_docs/version-2.7/integrations-in-rancher/cloud-marketplace/azure-marketplace-payg-integration/azure-marketplace-payg-integration.md

Can we replace the 2 FAQ sections with a single unified FAQ?
Reason: Simpler updates in the future.

I already have that unified version in .md format here.  
Happy to upload via a PR, but it will need linking from the the main docs.

Let me know how you want to proceed.

Many Thanks

**Comment by LucasSaintarbor** [comment]
> There are currently 2 versions of the Rancher PAYG FAQ. One for Azure, One for AWS.
> 
> https://github.com/rancher/rancher-docs/blob/main/versioned_docs/version-2.7/integrations-in-rancher/cloud-marketplace/aws-marketplace-payg-integration/aws-marketplace-payg-integration.md
> 
> https://github.com/rancher/rancher-docs/blob/main/versioned_docs/version-2.7/integrations-in-rancher/cloud-marketplace/azure-marketplace-payg-integration/azure-marketplace-payg-integration.md
> 
> Can we replace the 2 FAQ sections with a single unified FAQ? Reason: Simpler updates in the future.
> 
> I already have that unified version in .md format here. Happy to upload via a PR, but it will need linking from the the main docs.
> 
> Let me know how you want to proceed.
> 
> Many Thanks

Hi @stephenmogg! Although I understand the ask to simplify updates for the future, it may be better to keep the FAQ sections separate. For example, If a user is getting started with the AWS PAYG option, they will land on the top-level page, [AWS Marketplace Pay-as-you-go (PAYG) Integration](https://ranchermanager.docs.rancher.com/v2.7/integrations-in-rancher/cloud-marketplace/aws-marketplace-payg-integration), which contains information/FAQs specific to AWS Marketplace users. If we create a unified FAQ, the AWS user would have to navigate outside the "AWS Marketplace Pay-as-you-go (PAYG) Integration" section to see a list of FAQs. There are some small differences between the AWS and Azure FAQs, and it seems like more work for the user to figure those out with a unified FAQ.
