### ISSUE TITLE
Add documentation for OCI feature in Apps & Marketplace Section

### ISSUE THREAD

**Issue by rohitsakala** [rancher/rancher-docs#1151]
## Related Issues

GitHub Issue - https://github.com/rancher/rancher/issues/29105
UI Issue - https://github.com/rancher/dashboard/issues/9815
GitHub PR - https://github.com/rancher/rancher/pull/43823

## Summary

There is a new feature that is going to be released in the Apps and Marketplace category. That is support for OCI-based Helm repositories.

h4. Acceptance criteria
* There are docs covering the functionality of the OCI Helm repository feature in Apps & Marketplace 
* There are docs covering debugging and logging for any known OCI Helm repository issues
* There are docs covering the limitations of the feature.

**Comment by gunamata** [comment]
Initial content is available on SURE-7757

**Comment by martyav** [comment]
Additional links:

- rancher/rancher: https://github.com/rancher/dashboard/issues/9815
- Helm official docs: https://helm.sh/docs/topics/registries/
