### ISSUE TITLE
Update Rancher Kubernetes API Project creation workflow doc to include annotation requirement for Cluster Member

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher-docs#1153]
## Related Issues
https://github.com/rancher/rancher/issues/44638#issuecomment-1977227560

## Summary
When using the **Rancher Kubernetes API** to create a project, a `cluster member` must include the annotation "`field.cattle.io/creatorId: user-id`". This annotation is necessary for the project to work with the "**`get`**" command and for the project to be visible in the UI when the cluster member is logged in.

**Link to the page requiring an update**: https://ranchermanager.docs.rancher.com/api/workflows/projects
A note suggesting the annotation requirement would be beneficial for users. 

**Note**: This annotation is not needed for cluster owner or admin.

**Comment by martyav** [comment]
@Priyashetty17 This might be a silly question -- does the user enter their own user ID, or do they enter `cluster-member-user-id` verboten?

**Comment by Priyashetty17** [comment]
@martyav the user enters their own user ID. I updated the annotation in the summary ^^ to reference `user-id `to avoid confusion
