### ISSUE TITLE
Amazon in-tree to out-of-tree migration guide contradicts UI behavior 

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/rancher-docs#1155]
## Related Issues
https://github.com/rancher/dashboard/issues/9204
## Summary
The instructions in the aws cloud provider migration guide don't match UI behavior, which is confusing. The guide states

> You can migrate from an in-tree to an out-of-tree AWS cloud provider on Kubernetes 1.26 and earlier. All existing clusters must migrate prior to upgrading to v1.27 in order to stay functional.

However, through the UI users can upgrade to 1.27 at the same time that they're changing cloud providers. That is the only time that users can change the cloud provider through the UI, so migrating before upgrading to 1.27+ is not possible through the UI.

**Comment by martyav** [comment]
I think we also need to include a description of how to go about performing the migration through the UI. The current page doesn't have any steps mentioning the Rancher UI, so if we bring up the UI without any further mentions of it on the page, it leaves readers hanging.

**Comment by martyav** [comment]
Forget previous comment, one of the linked pages from the out-of-tree migration guide includes UI instructions.
