### ISSUE TITLE
Document new Extensions for 2.7

### ISSUE THREAD

**Issue by jtravee** [rancher/rancher-docs#116]
References: 

[Background docs](https://confluence.suse.com/pages/viewpage.action?spaceKey=EN&title=UI+Plugins)
[UI Sync](https://mysuse-my.sharepoint.com/:v:/r/personal/gkorhonen_suse_com/Documents/Recordings/UI%20Plugins%20sync%20with%20QA%20and%20Docs-20220914_083236-Meeting%20Recording.mp4?csf=1&web=1&e=sVvgYb)

**Comment by btat** [comment]
Addressed via https://github.com/rancher/rancher-docs/pull/281.
