### ISSUE TITLE
Overlay test for Windows nodes

### ISSUE THREAD

**Issue by mrolmedo** [rancher/rancher-docs#1228]
## Related Issues
SURE-8128

## Summary

The overlay test, https://ranchermanager.docs.rancher.com/troubleshooting/other-troubleshooting-tips/networking, only works in Linux nodes. If the clusters run Windows worker nodes, the container swiss-army-knife does not run.

**Comment by martyav** [comment]
@mrolmedo do you happen to know if Windows nodes trigger the `exec user process caused: exec format error` message in pod logs, as ARM nodes do?

**Comment by mrolmedo** [comment]
@martyav Sorry for the delay! I got this error in the Rancher UI "ImagePullBackOff (Back-off pulling image "rancherlabs/swiss-army-knife")" and more detailed when I catch the namespace events:
`<img width="662" alt="overlayWindows" src="https://github.com/rancher/rancher-docs/assets/96732346/c8b21ead-9ea6-4362-905f-a1ea0abfee06">`"     Warning   Failed             pod/overlaytest-kjd6p   Failed to pull image "rancherlabs/swiss-army-knife": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/rancherlabs/swiss-army-knife:latest": failed to extract layer sha256:030309cad0ba82b098939419dcb5e0a95c77d2427d99c44a690ecab59f80a487: Failed to safefile.OpenRelative failed in Win32: open \\?\C:\var\lib\rancher\rke2\agent\containerd\io.containerd.snapshotter.v1.windows\snapshots\38\var\lib\dpkg\info\gcc-8-base:amd64.list: path contains invalid character `:` (0x1f) var\lib\dpkg\info\gcc-8-base:amd64.list: unknown"

<img width="662" alt="overlayWindows" src="https://github.com/rancher/rancher-docs/assets/96732346/9f9d9b9c-81c7-4adc-8147-5e4d52b2bf3d">
