### ISSUE TITLE
Docker machine link redirects to Docker Desktop documentation

### ISSUE THREAD

**Issue by andrew-morris-rgs** [rancher/rancher-docs#1281]
## Related Issues

The webpage: 
https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-node-drivers 

has a link to "docker-machines" but that link redirects to https://docs.docker.com/desktop/ which does not explain the topic at all. I also could not find any docker machine documentation on dockers home page.

**Comment by martyav** [comment]
I did a little research. The Docker Machine repo is now archived and the project is deprecated. 

From https://github.com/docker/machine/issues/4894#issuecomment-897601827:

> We are not actively maintaining this project and see [Docker Desktop](https://www.docker.com/products/docker-desktop) as its successor for container development on macOS and Windows. I've added an item on our https://github.com/docker/roadmap/issues/245 where you can leave us feedback.

From https://github.com/docker/roadmap/issues/245:

> The Docker Machine project started in 2014 to make it easier to setup and run Docker in a virtual machine. One of the major use cases for this was to make it easier to use Docker on macOS and Windows. Since its release in 2016, [Docker Desktop](https://www.docker.com/products/docker-desktop) has been seen as the replacement for Docker Machine to develop with containers on macOS and Windows. Not only does Docker Desktop provide a Docker API endpoint but it also provides transparent handling of file sharing and networking between the host and VM which make container development easier.

[Rancher: Node Drivers](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-node-drivers#developing-your-own-node-drivers) contains a link to https://docs.docker.com/machine/ but that page has been removed and the Docker site redirects visitors to https://docs.docker.com/desktop/ instead.

Curiously enough, Rancher maintains its own fork of Docker Machine at https://github.com/rancher/machine. The README on that repo points to the dead https://docs.docker.com/machine/ link.

The Rancher fork notes:

> This project is intended to be embedded and executed by the full [Rancher](https://github.com/rancher/rancher) product and the stand alone cli functionality will remain but the human use of it will not be the primary focus as we will expect inputs provided by other things like Terraform or UIs.

@jiaqiluo do you know how/if this effects user-developed node drivers? The docs section that contains the dead Docker Machine link is specifically about users developing their own drivers.
