### ISSUE TITLE
[2.9.0] Add deprecation warning on SRIOV chart

### ISSUE THREAD

**Issue by btat** [rancher/rancher-docs#1297]
Related to https://github.com/rancher/dashboard/issues/11042

From [#11042](https://github.com/rancher/dashboard/issues/11042):

> SRIOV charts will no longer be updated in https://github.com/rancher/charts because their new home is https://github.com/suse-edge/charts.

For the docs portion of this change:

1. We need to add a warning so that users know the SRIOV chart is deprecated and that it will be removed in v2.10. A [suggestion warning](https://github.com/rancher/dashboard/issues/11042#issuecomment-2122924354) has been made for the UI, which we can use.
3. A migration guide helping users move to the new chart.

**Comment by manuelbuil** [comment]
We have tested this with @mgfritch and it works seamlessly by adding the new edge chart repo and then installing the sriov chart there using the same name as the old chart. Behind the curtains, the command used is `helm upgrade` so all sriov get upgraded to the new chart
