### ISSUE TITLE
Add SLO Configuration for SAML Providers

### ISSUE THREAD

**Issue by sunilarjun** [rancher/rancher-docs#1331]
Related to https://github.com/rancher/dashboard/issues/10941

Per [comment](https://github.com/rancher/dashboard/issues/10941#issuecomment-2154569175):

> the documentation for rancher manager will need updating in regards to how they should configure the Single Logout on each of the SAML providers. Ex: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-okta-saml

The Jira (SURE-3572) also has outlines of the new UX user experience for context.

**Comment by martyav** [comment]
Slated for 2.10 but we don't have a milestone for that yet as it's too far out

**Comment by btat** [comment]
Addressed by https://github.com/rancher/rancher-docs/pull/1335.
