### ISSUE TITLE
Link to "Settings for etcd tuning" no longer valid

### ISSUE THREAD

**Issue by teambvd** [rancher/rancher-docs#1358]
## Summary

Within the "[Checklist for Production-Ready Clusters](https://ranchermanager.docs.rancher.com/v2.8/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/checklist-for-production-ready-clusters#networking)" section of the user guide, a link is provided purporting to provide `etcd` tuning recommendations:

![etcd-tuning-link](https://github.com/rancher/rancher-docs/assets/70113838/1626c344-ce64-4af8-90ab-735d2782239b)

The link points to `https://coreos.com/etcd/docs/latest/tuning.html`, but with coreos.com no longer existing, this now redirects to [etcd.io](https://etcd.io/). Checking archive.org, it looks like this link was invalidated sometime in 2019, as the first instance I can find that has a valid page is back in [2018](https://web.archive.org/web/20181002050041/https://coreos.com/etcd/docs/latest/tuning.html).

I'm not sure the link is still needed given many of the improvements to `etcd` since then, but at the very least, the link should likely be modified to point elsewhere, if not removed.

**Comment by martyav** [comment]
Looks like the page now lives at https://etcd.io/docs/v3.5/tuning/.
