### ISSUE TITLE
Port requirements for Monitoring and other optional Rancher features

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher-docs#136]
I couldn't find a note of the port 9796 needing to be exposed in the Rancher docs, or if any others are required.  There is conflicting info online and it looks like some ports can be modified (and may have been since thxcode notes in https://github.com/rancher/rancher/issues/17957 that 9100 is required but I see nothing expose there on my cluster).
It is important that we have this information readily available. 

I've created PRs https://github.com/rancher/docs/pull/2489 and https://github.com/rancher/docs/pull/2490 to expose at least this port on the monitoring page, but we need to find out if others are required and probably expose the information in a better way.  

I think it maybe it makes sense to add to https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/node-requirements/#networking-requirements/ and maintain it as our central reference page?  (I think that's the goal here?  Can't actually see most of the items on this page so opened rancher/docs#2492)

**Comment by btat** [comment]
> From discussion about #451 -- in the current version of Rancher, v2 monitoring uses PushProx so that users generally don't have to open these ports. However, they may still need to open ports if:
> 
>     1. They upgraded from a previous Rancher install that had v1 monitoring turned on
> 
>     2. They disable Pushprox
> 
> 
> In 2020, when this issue was opened, v2 had just been released and v1 was still the most common. In 2023, all of our latest documentation prioritizes v2 and use-case 2 (PushProx disabled) is an edge case we don't yet test for.
> 
> @geethub97 @btat How do we feel about closing this issue? It had some value for tracking monitoring requirements for a while but I think it's just confusing to keep it open at this point.

+1 on closing based on that info.
