### ISSUE TITLE
New installation requirement: http/2

### ISSUE THREAD

**Issue by moio** [rancher/rancher-docs#1364]
## Related Issues
[Internal link](https://jira.suse.com/browse/SURE-8299) to a customer case that brought this issue up.

## Summary

HTTP/2 is a network protocol introduced and widely supported by most browsers in 2015 (https://caniuse.com/http2). The protocol is substantially different from the earlier HTTP/1.1 protocol, and several changes were introduced to improve web application performance.

The Rancher UI requires support of this protocol to operate efficiently:

- in browsers, and this is already documented
- in any potential third party load balancer or similar network infrastructure sitting between the browser and the Rancher cluster, **this is not yet documented**

Note that the Rancher UI will fall back to HTTP/1.1 if HTTP/2 is not available, although this will create performance issues.

### Policy notes

This is a general, non-hardware requirement which is especially critical in high performance/high scalability cases, but in some pages (such as the App Catalog) is important regardless of the Rancher installation size.

The use of HTTP/2 compatible load balancers should be _recommended_ in general and for community users, note however that it should be worded as _requirement_ to get SUSE Support help for paying customers (this was already discussed and approved with PM, specifically @asettle and @CamrynCarter).

**Comment by asettle** [comment]
@btat @LucasSaintarbor @sunilarjun I spoke with Silvio about this issue in particular, but also, we should really consider including a "requirements and recommendations" section at the beginning of the guide. We are not prescriptive enough in our documentation at the moment and we're allowing freedom of movement in the product that will eventually create larger issues with the different supported configurations.

If we were to have version X release of Rancher it should be clear that it supports versions X and Y of Longhorn and Harvester respectively, but also, these are the clear HW and SW we have tested and recommend. For example: https://documentation.suse.com/ses/7.1/single-html/ses-deployment/#storage-bp-hwreq 

Thoughts? CC @gunamata @jillian-maroket @jhkrug @martyav @nunix

**Comment by gaktive** [comment]
Bullseye leans towards having http/2 listed as a recommendation for 2.9.0+ and maybe throughout our version history. @mattfarina is checking if a requirement should be considered down the road.
