### ISSUE TITLE
[v2.9.0] optional filter on AzureAD auth group memberships

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher-docs#1370]
## Related Issues

https://github.com/rancher/rancher/issues/42940
https://jira.suse.com/browse/SURE-5641

## Summary
Created filter so that only groups that begins with a specific name are being returned instead of all the groups the user has attached to his account.

thus, reducing the noise in the logs

"we have many users that have a lot of groups and we have discovered that it generates a lot of logs because all of their groups are displayed in the logs"

## Details
The backend, specifically the AzureADConfig structure is extended with a new field groupMembershipFilter.
The field takes a string and passes this directly into filter clause of the group membership query.
This means that the field has to contain a filter clause in OData syntax.
Example: startswith(userPrincipalName,'fresh')
See also https://learn.microsoft.com/en-us/odata/concepts/queryoptions-overview#filter

**Comment by samjustus** [comment]
we hope to add more information as QA tests it - initial case provided by customer isn't clear on details - however the filter is up and working in 2.9.0 - we don't think this needs anything extensive

**Comment by martyav** [comment]
@samjustus since this is running in 2.9, should we aim to document this for the upcoming release? Or will the info we need to document it come after the release is out?

**Comment by samjustus** [comment]
https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-azure-ad should be updated

more context: https://suse.slack.com/archives/C06E7E4KH1D/p1720554781995569?thread_ts=1720548031.261329&cid=C06E7E4KH1D

cc @andreas-kupries

**Comment by anupama2501** [comment]
@martyav this only applies to azure AD auth provider but not AD auth provider. So, we do not have to update https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-active-directory..

**Comment by martyav** [comment]
@anupama2501 
Doesn't the feature relate to filtering logs? I listed that page as one of two to **possibly** update because the feature seemed to be related to logging.

**Comment by anupama2501** [comment]
ah no! this includes rancher and audit logs only. we do not have to include anything related to logging in here.

**Comment by martyav** [comment]
Related:

- https://github.com/rancher/rancher/issues/42940#issuecomment-2240095280
- https://github.com/rancher/rancher/issues/42940#issuecomment-2242296592
