### ISSUE TITLE
[2.9.0] - Update Feature Flags - uiextension

### ISSUE THREAD

**Issue by sunilarjun** [rancher/rancher-docs#1403]
Related to https://github.com/rancher/rancher-docs/pull/1301

Need to update the feature flag page with the new field `uiextension` coming in v2.9.0.

https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-references/feature-flags

**Comment by martyav** [comment]
@sunilarjun I don't think we have a PR for this yet. I can take it if you're too busy
