### ISSUE TITLE
Search not working when switched to Chinese docs

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher-docs#143]
rancher 2.6 documentation is switched to Chinese, and does not support Chinese or English search。、

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/19684717/190369741-82970e53-464a-417e-8199-d356d4cb98d7.png">

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/19684717/190369795-5d49c200-fed2-4c63-958f-b94cc906b0bf.png">

**Comment by btat** [comment]
Hi @kingsd041, our search index should now include results from the Chinese docs. Please reopen this issue if it's still not working for you.
