### ISSUE TITLE
[2.10] New Feature Flag: managed-system-upgrade-controller 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher-docs#1504]
## Related Issues
https://github.com/rancher/rancher/issues/42448

## Summary

The `managed-system-upgrade-controller` is a new feature flag being introduced in Rancher v2.10, and we would like to include it on the [Feature Flags](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-references/feature-flags) page in the Rancher documentation.

## Details

**Feature Flag Name**: managed-system-upgrade-controller
**Default Value**: `true` 
**Status**: GA
**Available As Of**: v2.10.0
**Additional information**: This feature flag enables the installation of the system-upgrade-controller app in downstream RKE2/K3s clusters, currently limited to imported clusters and the local cluster, with plans to expand support to node-driver clusters.

**Comment by btat** [comment]
Addressed by https://github.com/rancher/rancher-docs/pull/1542.
