### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by vincent99** [rancher/rancher-docs#173]
Edited by Catherine in February 2020:

After a discussion with Vince, we're going to do this in a slightly different order.

### Part 1 - Basics

- Use the API in the browser
- Get API Keys
- Make requests - say actions are POSTs
- Levels of scope - describe scopes of API
- Show where types and schemas are

### Part 2 - Document operations that have a global scope
Focus on showing how to use the Rancher API for manipulating things outside the scope of a cluster, because the kubectl CLI can be used to manipulate resources within clusters.

We will show how to:

- Initially set up a Rancher server
- Change settings
- Create a custom cluster (custom clusters use an RKE config type, and other configs are used for other clusters)
- Create an imported cluster
- RBAC
- Authentication, adding users and groups
- Node templates
- Cloud credentials

### Long term goals for API docs

- The Rancher API view should eventually be documented with a similar format and similar process used in the Kubernetes API reference: https://kubernetes.cn/docs/reference/generated/kubernetes-api/v1.13/
- Automated API doc generation, starting with types, which are currently listed under ‘schemas’ in the Rancher API at [Rancher server URL]/v3/schemas
- Create JSON or YAML schema generated from the Rancher API view in order to make Swagger docs
- Add more human-readable descriptions to types and other API resources
- Pipelines and custom catalogs with the Rancher API

Edit October 20 2020:

The requirements for a fully documented API reference will be:

- Must document all types
- Must list all of the fields, options, actions, sortings, etc
- Must describe the fields, what type they are, what kind of values are allowed, or which ones are required
- Any examples must be tested
- The API reference must be organized by the scope of the resources, with global scoped, cluster scoped, and project scoped resources

**Comment by btat** [comment]
Consolidating into https://github.com/rancher/rancher-docs/issues/583.
