### ISSUE TITLE
Convert Hugo shortcodes

### ISSUE THREAD

**Issue by btat** [rancher/rancher-docs#19]
The Hugo shortcodes folder was originally removed during the initial Docusaurus set up and the corresponding shortcodes have not been converted for compatibility with Docusaurus.

E.g. `{{< release-channel >}}` on https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades#for-upgrades-with-cert-manager-older-than-080

**Comment by catherineluse** [comment]
This is addressed by https://github.com/rancher/rancher-docs/pull/24
