### ISSUE TITLE
Provisioning redhat/centos  by preventing "yum install curl"

### ISSUE THREAD

**Issue by prabhassasi** [rancher/rancher-docs#207]
Information about the Cluster

Kubernetes version: v1.23.10
Cluster Type (Local/Downstream): downstream
If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): RKE VMware vSphere but should effect any node-driver cluster.
Cluster installed by using nodetemplate

**Issue**

When provisioning a new downstream cluster with RHEL nodes, the provision phase doesn't work, it fails on the installation of curl even if curl is already installed on the node.

**To Reproduce**

Create a new downstream cluster with RHEL nodes where the docker is pre-installed in the image or no repositories are added.

**Result**

the provisioning phase fails with this error message
Error creating machine: RHEL ssh command error: command: sudo -E yum install -y curl err: exit status 1 output: Updating Subscription Management repositories.

**Fix**

In node template under engine option use Docker install as "None" . This will bypass the checking of curl and docker installation

![image](https://user-images.githubusercontent.com/54670152/190944364-dd332716-8cf3-450f-9c4e-2024dbd869d3.png)

Spin up the node after updating this in the node template

**Comment by dkeightley** [comment]
Related issue for the `none` driver install URL - https://github.com/rancher/rancher/issues/27646
