### ISSUE TITLE
SSO/Auth Configuration through Infrastructure as Code

### ISSUE THREAD

**Issue by RamazanKara** [rancher/rancher-docs#246]
SSO / Auth Configuration is currently only possible through UI (and possibly API Calls, which are not documented). The current way of bootstrapping a local user first and then configuring SSO through UI is cumbersome. 

We would rather be able to configure SSO through the Helm Chart and bootstrap Rancher that way to really be able to deploy Rancher the GitOps way.

**Comment by btat** [comment]
It looks like you've already created a [RFE on rancher/rancher](https://github.com/rancher/rancher/issues/39234). Since there's no documentation component at this point I'm going to close this one.
