### ISSUE TITLE
Update any remaining <h1> headers to be <h2> in order that linking works properly

### ISSUE THREAD

**Issue by jtravee** [rancher/rancher-docs#252]
We need to update any outstanding Level 1 headers to be Level 2 headers as Docusaurus does not support h1 anchors.

See also: [Slack thread](https://suse.slack.com/archives/C02DQMPRA1E/p1665467204645629)

**Comment by akshat5302** [comment]
Hey, @jtravee is this issue resolved?

**Comment by jtravee** [comment]
> Hey, @jtravee is this issue resolved?

Hi @akshat5302, no we have not yet done this; we are in the middle of restructuring our docs after the initial rollout. Once we've completed this, we will be implementing these changes (next few weeks projected).
