### ISSUE TITLE
Missing hardware requirements for RKE2

### ISSUE THREAD

**Issue by gkumarchilakala** [rancher/rancher-docs#258]
Hi Rancher Team,

According to the Rancher 2.6 documentation, the hardware requirements for RKE2 based cluster for Rancher is incomplete.

https://docs.ranchermanager.rancher.io/pages-for-subheaders/installation-requirements

The Hardware requirements beyond 15 clusters is not specified for RKE2, where for RKE and K3S, the hardware requirements are specified till 2000 clusters.

Since Rancher tells us that RKE2 will be the future, this kind of in complete information won't provide any confidence to the customers.

Looking forward to seeing the complete hardware requirements for RKE2

Thanks,
Goutham Kumar

**Comment by btat** [comment]
Thanks for the request @gkumarchilakala, I'm going to close this one to keep things consolidated since the request for updating that page (and in the turn RKE2 section) is being tracked in https://github.com/rancher/rancher-docs/issues/103.
