### ISSUE TITLE
Mistakes in the port requirements of Rancher nodes 

### ISSUE THREAD

**Issue by belgaied2** [rancher/rancher-docs#266]
# Problem
The port requirements have multiple clarity, completeness or accuracy issues at [this link](https://docs.ranchermanager.rancher.io/getting-started/installation-and-upgrade/installation-requirements/port-requirements):

- In the Rancher Nodes on RKE section:
  - The IP shown for git.rancher.io are outdated: ~`35.160.43.145,35.167.242.46,52.33.59.17`~. A `nslookup` shows as of today `34.208.213.149` and `52.36.54.134`, but since this can change in the future, I would use the same approach as away in the docs: just put `git.rancher.io` with no ip addresses.
- In the Rancher Node for RKE2 section:
  - For port `9345`: The source can also be other `server `nodes, not only `agents` as it is used for node registration. The description is also wrong: ~~`Kubernetes API`~~ should be `Node Registration, port should be open on all server nodes to all other nodes in the cluster`
  - For Node port (`30000-32767`) : The protocol can be TCP but also **possibly UDP**
  - Ports `8080` and `8443` should not appear because these exist only with `rancherd` because it creates a `hostPort` to access Rancher on all nodes. By default, Rancher is installed using Ingress Controller, which opens ports `80` and `443` instead. Meaning, the port `8080`should be replaced by `80`, and the port `8443` should be replaced by `443`, with the mention that all applications using Ingress Controller should be the same.

**Comment by martyav** [comment]
@belgaied2 Hi, I started looking into older issues. Could you clarify this part: 

>  with the mention that all applications using Ingress Controller should be the same

Thanks!

**Comment by btat** [comment]
Addressed by #390.
