### ISSUE TITLE
user access for seeing and accessing monitoring dashboards

### ISSUE THREAD

**Issue by kourosh7** [rancher/rancher-docs#270]
The documentation should specify that a user needs to have the View Monitoring role in the project where Monitoring is installed to access the monitoring dashboards. Otherwise, the dashboards are grayed out.

**Comment by btat** [comment]
Possibly related to #963.

cc @martyav

**Comment by martyav** [comment]
Related to https://github.com/rancher/dashboard/issues/4466

**Comment by kourosh7** [comment]
@btat @martyav To be honest, I'm slightly confused about what the fix for https://github.com/rancher/dashboard/issues/4466 is. It seems the original expected and actual results have changed throughout the comment thread. 

Back to the topic of this issue. The most common issue I see raised by customers regarding monitoring and RBAC is that users see the links in the 'Monitoring' page as grayed out. The documentation needs to cleary say what permissions are required to allow this. In my testing, the only way I have seen this is by:

1.  Installing or moving the **cattle-monitoring-syste**m namespace to a project where the users have **View Monitoring** role 
2.  The users need at least **Read Only** role on one project in the cluster

If these are indeed the required steps to see the Monitoring dashboards available (not grayed out) in the cluster, then the documentation should specify that. The comment https://github.com/rancher/dashboard/issues/4466#issuecomment-1771627358 says that's a workaround. But to me, that seems like the solution. Clarity is needed here and it needs to be explicit in the documentation.
