### ISSUE TITLE
Missing Documentation: Rancher Monitoring requires port 10254

### ISSUE THREAD

**Issue by stefanlasiewski** [rancher/rancher-docs#300]
Rancher Monitoring requires that the host firewall be open on port 10254. Prometheus will scrape metrics from this port. However, this port is not correctly documented in the Rancher Docs.

There are two places where this could be documented:

1. https://docs.ranchermanager.rancher.io/pages-for-subheaders/monitoring-and-alerting , which does not mention port 10254.

2. The Rancher documentation at [Ports for Rancher Launched Kubernetes Clusters using Custom Nodes](https://docs.ranchermanager.rancher.io/v2.5/getting-started/installation-and-upgrade/installation-requirements/port-requirements#ports-for-rancher-launched-kubernetes-clusters-using-custom-nodes) uses a grid to explain the firewall requirements. In the following section, I'm looking at the "From Worker Plane Nodes", "To Worker Plane Nodes". Note footnote 4 in the box labeled "10254 TCP (4)".

![image](https://user-images.githubusercontent.com/142752/202578111-bdbfbd48-46ed-41c0-9911-0955c9e17084.png)

Footnote 4 says:

> 4. Local traffic to the node itself (not across nodes).

Users have pointed out this discrepancy in the docs in a couple previous issues, such as:
* https://github.com/rancher/rancher-docs/issues/136#issuecomment-1247331477

**Comment by martyav** [comment]
@stefanlasiewski I started looking into this issue. How should footnote 4 for the table be updated? 

> 4. Local traffic to the node itself (not across nodes).

**Comment by stefanlasiewski** [comment]
Hi @martyav, I would suggest that the documentation should say that for optional features such as Rancher Monitoring, port 10254 between nodes. I'm  not sure how to phrase that concisely.

**Comment by stefanlasiewski** [comment]
Yes, I think that may be it.
