### ISSUE TITLE
configure-azure-ad page for 2.6 shows API permissions needed for 2.7 instead of those needed for 2.6

### ISSUE THREAD

**Issue by tlatino** [rancher/rancher-docs#311]
For azure-ad in Rancher 2.6, the API permissions needed are users.read.all and group.read.all instead of directory.read.all like in 2.7 due to a change in permission structure. The update done for 2.7 has changed the 2.6 pages as well when they should have been kept separate. The text in 

https://github.com/rancher/rancher-docs/blob/main/docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-azure-ad.md 

needs to be updated to reflect the old permissions when looking at 

https://docs.ranchermanager.rancher.io/v2.6/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-azure-ad

and a new image will need to be created similar to

 https://github.com/rancher/rancher-docs/blob/main/static/img/api-permissions.png

 but with the old permissions

**Comment by martyav** [comment]
@tlatino @btat Looks like this has already been corrected.

**Comment by btat** [comment]
On the 2.6 page, the mismatch between the text and image mentioned above still needs to be fixed. Both the 2.6 and 2.7 pages use the same filename for the image so the 2.6 one was overwritten. @martyav could you please help update this.

**Comment by btat** [comment]
Fixed by #373.
