### ISSUE TITLE
Validate and update links to RKE2 docs

### ISSUE THREAD

**Issue by btat** [rancher/rancher-docs#356]
The RKE2 docs were [reorganized](https://github.com/rancher/rke2-docs/pull/1) recently so some of the links (docs.rke2.io) we use may no longer be valid (e.g. https://github.com/rancher/rancher-docs/pull/354). We should verify the links we use are still valid and update them if not.

**Comment by LucasSaintarbor** [comment]
Reviewed 214 links at https://docs.rke2.io/. 

- 210 links validated 
- 4 links need follow up

[RKE2 Docs - URL Check.xlsx](https://github.com/rancher/rancher-docs/files/10689935/RKE2.Docs.-.URL.Check.xlsx)
