### ISSUE TITLE
Document config requirement for monitoring on imported AKS clusters

### ISSUE THREAD

**Issue by catherineluse** [rancher/rancher-docs#377]
The context of this issue is that it was originally reported as a bug (https://github.com/rancher/dashboard/issues/4658) in monitoring V1. In order for monitoring to work on imported AKS clusters, `exporter-kubelets.https` had to be set to `true` in the Helm chart values. I think that that kind of requirement is better addressed in documentation than in a UI change because when the UI injects certain values, it can lead to version incompatibility issues with the chart.

However, I just searched the monitoring helm chart values (https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-monitoring/100.0.0%2Bup16.6.0/values.yaml) and I didn't immediately see the same config option available for RKE2.

Someone should ask Team 3 the question: for V2 monitoring on imported AKS clusters, does it require the V2 equivalent of `exporter-kubelets.https` set to `true`? If so, I would suggest documenting it in the Rancher docs about monitoring and in the monitoring helm chart README.

**Comment by brandond** [comment]
The monitoring v2 chart has different values than V1. For V2, the equivalent value is `kubelet.serviceMonitor.https` and it is set to true by default. There is no cluster-specific kubelet section (rke2Kubelet, rkeKubelet or so on), so there should not be anything to configured.
