### ISSUE TITLE
Install Rancher 2.x without internet connection

### ISSUE THREAD

**Issue by JingangLi** [rancher/rancher-docs#395]
Hi Rancher team,

I see in 1.X rancher doc, we have this link to teach how to install rancher without internet connection. https://rancher.com/docs/rancher/v1.3/en/installing-rancher/installing-server/no-internet-access/

But in 2.x rancher doc, we can't find it. Has it be removed from rancher product, or do you have new link of it?

Many thanks.

Rgds,
Jingang Li

**Comment by Martin-Weiss** [comment]
Search for "air gapped" - does this help? https://ranchermanager.docs.rancher.com/pages-for-subheaders/air-gapped-helm-cli-install

**Comment by JingangLi** [comment]
Hi @Martin-Weiss ,

Many thanks for the guide. I will read them and prepare the env. 

Rgds,
Jingang Li
