### ISSUE TITLE
Incorrect step for `Applying Resource Quotas to Existing Projects` instructions

### ISSUE THREAD

**Issue by btat** [rancher/rancher-docs#403]
From Slack

> It looks like step 4 here should be “Click Group by Project” otherwise, you can’t tell edit the Project.
https://ranchermanager.docs.rancher.com/pages-for-subheaders/manage-project-resource-quotas

**Comment by martyav** [comment]
Running through the steps myself, they are indeed misleading. The UI stacks two rows which both have sets of dots that hide "Edit config" options --
![image](https://user-images.githubusercontent.com/19174201/219093461-cef0b609-79e8-4058-ac42-8fa25e72330e.png)

However, only the top set of dots will take you to a page that includes a "Resource Quotas" tab --
![image](https://user-images.githubusercontent.com/19174201/219093983-0c334a3b-8a87-4a50-abff-6ee272d05867.png)

The bottom set's "Edit config" page does not -- 
![image](https://user-images.githubusercontent.com/19174201/219094627-7d10a4ae-6694-4652-9ca1-8d5dd4c94988.png)
