### ISSUE TITLE
Troubleshooting page for broken Helm release secrets due to PSP removals in k8s 1.25 upgrade

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher-docs#416]
**Summary:**
We need to add Troubleshooting docs to help users troubleshoot issues with k8s 1.25 upgrades as PSP CRDs are removed.

**Details:**
Existing users/customers run into serious problems with k8s 1.25 upgrades with PSP CRs or helm charts with PSP CRs in them.
Here is the confluence page that is documenting a lot of the changes going into Rancher Manager about how to handle PSP removals for upgrades:https://confluence.suse.com/pages/viewpage.action?pageId=1166836296

**Comment by martyav** [comment]
@jiaqiluo Hi, wanted to check in as to what content should be published concerning this issue.

**Comment by stormqueen1990** [comment]
Another related issue: rancher/rancher-docs#488

**Comment by jiaqiluo** [comment]
Hi @martyav, I think the PR for issue #488 contains sufficient information to address this request. (Thanks @stormqueen1990 for chiming in! ) 

If you want a separate page for troubleshooting tips, we can think of how to reference it to the information on the pages in the above-mentioned PR once it is merged.

**Comment by martyav** [comment]
@jiaqiluo Ok, thank you, that makes sense.
