### ISSUE TITLE
How to upgrade to k8s 1.25 and what to note

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher-docs#417]
**Summary:**
We need to add docs on how to handle k8s 1.25 upgrades as PSP CRDs are removed.

**Details:**
Existing users/customers run into serious problems with k8s 1.25 upgrades with PSP CRs or helm charts with PSP CRs in them.
Here is the confluence page that is documenting a lot of the changes going into Rancher Manager about how to handle PSP removals for upgrades:https://confluence.suse.com/pages/viewpage.action?pageId=1166836296

**Comment by martyav** [comment]
How do you feel about closing as a duplicate of issue https://github.com/rancher/rancher-docs/issues/487? We have an open PR at #498.
