### ISSUE TITLE
Docs for PSACT (PSA Configuration Templates)

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher-docs#418]
This is to add docs for PSACT (PSA Configuration Templates). 

@snasovich , Can you please tag people from your team who can provide docs context/content for PSACTs. Then, the docs team will review, refine and add to docs.

**Comment by martyav** [comment]
@snasovich Hi, Sergey, wanted to follow up on this. Do you have an estimate on when we should see more details on PSACTs from your team? Thanks!

**Comment by snasovich** [comment]
@martyav Apologies for missing these notifications.
I think from PSACT/cluster portion of this we would want to have something similar to https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/create-pod-security-policies
Could you please connect with @jiaqiluo as he has the most knowledge/understanding of PSACTs.

There is also projects/namespaces aspect of this (similar to https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/manage-projects/manage-pod-security-policies) and someone from @cbron / @samjustus team would be the best point of contact.

**Comment by martyav** [comment]
Hi, @snasovich we actually did connect, and I currently have an open PR: https://github.com/rancher/rancher-docs/pull/489.

The page added in the PR covers how to add a PSA config template to a cluster, how to edit, and how to add namespace exemptions. We still need to cover troubleshooting.

**Comment by jiaqiluo** [comment]
Hi @martyav, when we create or update a PSACT, Rancher validates the PSACT object based on k8s requirements to ensure all fields' values are valid; when we delete a PSACT, rancher checks if it is used by any cluster and rejects the operation if it is true. So there is not much that could be wrong with the PSACT itself, which makes it hard for me to think of any troubleshooting guides 🤣  

We can consider closing this issue if it sounds good to you. I am happy to provide more information if you have any questions.
