### ISSUE TITLE
[2.7.0] Remove v1 tools references from documentation. 

### ISSUE THREAD

**Issue by doflamingo721** [rancher/rancher-docs#42]
Rancher v1 istio and cis-benchmark charts were deprecated in rancher v2.5.0. So we need to remove the associated references in docs for v2.7.0. (All deprecations for v1 charts can be found here: https://github.com/rancher/rancher/releases/tag/v2.5.0)

Linked issues:
https://github.com/rancher/rancher/issues/37327
https://github.com/rancher/rancher/issues/37322

**Comment by btat** [comment]
Fixed by https://github.com/rancher/rancher-docs/pull/296.
