### ISSUE TITLE
clarify that Global Default Private Registry does not work when using namespaced registry on downstream RKE2

### ISSUE THREAD

**Issue by tlatino** [rancher/rancher-docs#428]
public page to be modified: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/global-default-private-registry

ISSUE: When creating a global private registry, users may want to use a namespaced registry such as "https://website.com/prod-registry". This will work if downstream clusters are RKE, but if they are RKE2, this will not work at the moment. SURE-5910 is put in for fixing this issue but it will take time. For now, users should be directed to https://docs.rke2.io/install/containerd_registry_configuration or new docs on configuring namespaced registries using mirrors/rewrites through the Rancher UI, which we do not currently have. 

For now, a warning that namespaced global private registries will not work in downstream RKE2 clusters without additional configuration using https://docs.rke2.io/install/containerd_registry_configuration. 

If more documentation on configuring through the UI will be necessary, the user will need to configure the global private registry, then configure the registry on each downstream RKE2 cluster. This is done by going to Cluster Management > rke2 cluster > Cluster Config > registries > Select "Configure advanced containerd mirroring and registry authentication options" and add the namespaced registry to the registry hostname and mirror endpoints.

**Comment by martyav** [comment]
@tlatino 

> new docs on configuring namespaced registries using mirrors/rewrites through the Rancher UI, which we do not currently have

I see you listed the steps for configuring the downstream registries. How does the user configure the global private registry in preparation for this? Thank you.
