### ISSUE TITLE
Rancher docs do not list the Rancher containers

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher-docs#429]
**Summary:**
The docs list the architecture abstractly but do not list deployments or pods on https://ranchermanager.docs.rancher.com/reference-guides/rancher-manager-architecture/rancher-server-and-components

As users must manage the workloads in the Rancher cluster, it's important that they be able to easily look up a list of the main resources Rancher deploys and what each are

**Comment by martyav** [comment]
That page is kept a bit loose because such a list would need frequent maintenance. We currently don't have a process in place to automatically generate such a list, but if you'd like to see that added you can open a feature request.

**Comment by sumitNITS** [comment]
Hi @Tejeev,

In order to look up the list of the main resources Rancher deploys and what they are, you can check that using the namespaces where you have deployed them. You can achieve the same using CLI or going inside the rancher admin account too! 

Hope this helps. Have a good day ahead!

Regards,
Sumit

**Comment by sumitNITS** [comment]
Hi @btat & @martyav,

I am having a rancher set up in a single node, following this issue can I contribute to the rancher documentation where I'll add the screenshot of the resources that the rancher deploys when we go as a single node rancher deployment

Thanks,
Sumit

**Comment by Tejeev** [comment]
@martyav This request came on the heals of a customer interaction. Could we maybe update the doc to show how someone might be able to get such a list dynamically when needed?

**Comment by Tejeev** [comment]
Actually @sumitNITS looks like he's commented on your PR to that affect
