### ISSUE TITLE
Add Amazon Marketplace listing to 2.7 docs

### ISSUE THREAD

**Issue by btat** [rancher/rancher-docs#454]
When https://github.com/rancher/rancher-docs/pull/421 was submitted, it was noticed that the documentation link[1] being added mentioned `Rancher Setup is designed to deliver the current stable version of Rancher. At the time of this writing, Rancher 2.6.10 is deployed`. Given this is the case, the proposed changes were instead applied to the 2.6 version of the page and any references to the marketplace listing were removed from the 2.7 docs.

The references removed in #421 should be added back when the docs/marketplace offering has been updated for Rancher 2.7,

[1] https://documentation.suse.com/trd/kubernetes/single-html/gs_rancher_aws-marketplace/

**Comment by martyav** [comment]
This has to wait until we get explicit go-ahead to add.
