### ISSUE TITLE
How to set hostNetwork:true for k8s 1.21 and up

### ISSUE THREAD

**Issue by mrolmedo** [rancher/rancher-docs#455]
**Summary:**
In K8s 1.21 and up, the ingress controller no longer runs in hostnetwork:true. The docs for [RKE](https://rancher.com/docs/rke/latest/en/config-options/add-ons/ingress-controllers/#configuring-network-options) and [[Rancher](https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/new-user-guides/kubernetes-resources-setup/load-balancer-and-ingress-controller/ingress-configuration)] outlines that. Based on https://github.com/rancher/rancher-docs/issues/378, and (https://github.com/rancher/rancher/issues/35943#issuecomment-1055513521), IMHO, the docs should include the steps on how to set up or how to modify this parameter in Rancher Custom cluster or clusters launched with rke up. I´d also include more details about the tcp udp services impacted. For instance,  For Kubernetes v1.21 and up, all services exposed via TCP or UDP, set up in ConfigMap tcp-services or udp-services in the ingres-nginx namespace, will stop working if the hostnetwork:true is not set.
Thanks for your attention.

SURE-6006

**Comment by martyav** [comment]
@snasovich would you be able to assist with instructions on how to set hostNetwork:true for k8s 1.21 and up (or ping somebody who can)?

**Comment by snasovich** [comment]
@martyav , hopefully @kinarashah can help with this.

**Comment by kinarashah** [comment]
@martyav HostNetwork can be configured by setting network options in the cluster.yml https://rke.docs.rancher.com/config-options/add-ons/ingress-controllers#configuring-network-options 

```
ingress:
  provider: nginx
  network_mode: hostNetwork
  // other fields
```

**Comment by martyav** [comment]
@kinarashah is there a way to do this through the Rancher UI, or do you have to edit the cluster yaml?

**Comment by martyav** [comment]
@kinarashah Just following up with the last question. See above. Thank you!
