### ISSUE TITLE
Enabling "View in API" button

### ISSUE THREAD

**Issue by btat** [rancher/rancher-docs#460]
Request from Slack

> A user was looking for the view API button which is now disabled by default and the user has to enable the Developer tools from the preferences. So, I think we can mention where to enable to view-API if the user wants to see the command from the UI and uses it
>
> I would suggest to update https://ranchermanager.docs.rancher.com/v2.6/pages-for-subheaders/about-the-api to make this clear

**Comment by predatorprasad** [comment]
can you elaborate on where the changes need to be made

**Comment by btat** [comment]
> can you elaborate on where the changes need to be made

I updated the issue description to include the suggested page where this info could be added. There may be additional/better locations, but that will be determined once someone from the team picks this issue up.

**Comment by martyav** [comment]
This seems like a good place to put instructions: https://ranchermanager.docs.rancher.com/v2.6/pages-for-subheaders/about-the-api#capturing-rancher-api-calls

**Comment by btat** [comment]
2.6 and 2.7 will have different instruction sets due to the redesign described in https://github.com/rancher/dashboard/issues/6289.
