### ISSUE TITLE
Add instructions for how to use PSACT as the replacement of PSA  

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher-docs#462]
Rancher v2.7.2 supports configuring PSA on rke1/rke2/k3s clusters by using the PSACT.
We need to update Rancher docs to add at least the following:
- What is PSACT and how to manage it
- how to configure PSACT on the downstream rke/rke2/k3s cluster 

Links:
- main issue in rancher/rancher https://github.com/rancher/rancher/issues/38701

**Comment by martyav** [comment]
@jiaqiluo do you have additional information or a draft on how PSACTs can be added/edited through the Rancher UI?

**Comment by jiaqiluo** [comment]
hi @martyav , I think [this PR](https://github.com/rancher/rancher-docs/pull/479) is a good starting point. Could you help add the following information to Rancher docs? 

1. User can add or edit PSACT in the following page in rancher UI
<img width="1871" alt="Screenshot 2023-03-10 at 10 23 16 AM" src="https://user-images.githubusercontent.com/6218999/224382088-6db9ef40-afa9-4996-942e-5406fb4e00e1.png">

2. User can assign PSACT when creating/editing RKE1/RKE2/K3S node-driver/custom clusters in rancher UI.

<img width="1295" alt="Screenshot 2023-03-10 at 10 25 03 AM" src="https://user-images.githubusercontent.com/6218999/224382386-df5e4cf5-e61f-4bb3-a2f9-111cd1ea43c2.png">

**Comment by martyav** [comment]
@jiaqiluo Thanks. I haven't moved on this yet because I'm undecided on if this should go on the PSS page or on its own page. 

Looking at the screenshot -- Is PodSecurity Admission (no space) a typo?

**Comment by macedogm** [comment]
Question: do we already have a UI issue to address the above typo? Asking to avoid creating a duplicate.

**Comment by martyav** [comment]
> Question: do we already have a UI issue to address the above typo? Asking to avoid creating a duplicate.

Just created https://jira.suse.com/browse/SURE-6022
