### ISSUE TITLE
Instructions for Preparing Hardened Imported/Custom RKE2/K3s Cluster for Upgrade from 1.24 to 1.25 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher-docs#487]
We would like to add instructions for preparing hardened imported/custom RKE2/K3s clusters for the upgrade from 1.24 to 1.25. 
Because Rancher does not manage the nodes, user needs to prepare the nodes outside of Rancher for the switch from PSP to PSA. 

The instructions are summarised based on associated GH issues in rancher/rancher.

Could Doc Team help to fit them into the documentation? 
 
### 1. Prepare Imported k3s Cluster (https://github.com/rancher/rancher/issues/40739) 

The steps in the [K3s docs](https://docs.k3s.io/known-issues#:~:text=Upgrading%20Hardened%20Clusters%20from%20v1.24.x%20to%20v1.25.x) are sufficient for preparing the upgrade except that we should use the PSA config file for Rancher (attached at the end of the issue) instead of the one in the docs. 
 
After the preparation, we can edit the cluster to upgrade the Kubernetes version in Rancher UI. 

### 2. Prepare Imported RKE2 Cluster (https://github.com/rancher/rancher/issues/40738)

To prepare the cluster for the upgrade, instead of following the steps in [the RKE2 docs](https://docs.rke2.io/known_issues#ingress-in-cis-mode:~:text=Upgrading%20Hardened%20Clusters%20from%20v1.24.x%20to%20v1.25.x) we need to do the following:

First, on each node, create the file `rancher-psact.yaml` at the directory `/etc/rancher/rke2`  with the PSA config file for Rancher (attached at the end of the issue). Both the filename and the directory can be customized. 

Then, on each node, edit the RKE2 config file with the following two changes:
1.  switch the `profile` from `cis-1.6` to `cis-1.23` 
2. set the path for the pod security admission config file to the above file 

for example 
```
profile: "cis-1.23"
pod-security-admission-config-file: /etc/rancher/rke2/rancher-psact.yaml
```

After the preparation, we can edit the cluster to upgrade the Kubernetes version in Rancher UI. 

### 3. Prepare Custom k3s Cluster (https://github.com/rancher/rancher/issues/40737) 

User needs to edit the cluster to do the following 
- remove `PodSecurityPolicy` from `kube-apiserver-arg.enable-admission-plugins` (via edit as YAML)
- set PSACT to  `rancher-restricted` (via either edit as From or YAML) 
- change the Kubernetes version to 1.25

Now, user can save the cluster to start the upgrade 

### 4. Prepare Custom RKE2 Cluster (https://github.com/rancher/rancher/issues/40736)

User needs to edit the cluster to do the following 
- set PSACT to  `rancher-restricted`
- change the `profile` to `cis-1.23`
- change the Kubernetes version to 1.25

Now, user can save the cluster to start the upgrade 

## Reference

The following is the PSA config file for Rancher:

```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    defaults:
      audit: restricted
      audit-version: latest
      enforce: restricted
      enforce-version: latest
      warn: restricted
      warn-version: latest
    exemptions:
      namespaces:
      - ingress-nginx
      - kube-system
      - cattle-system
      - cattle-epinio-system
      - cattle-fleet-system
      - longhorn-system
      - cattle-neuvector-system
      - cattle-monitoring-system
      - rancher-alerting-drivers
      - cis-operator-system
      - cattle-csp-adapter-system
      - cattle-externalip-system
      - cattle-gatekeeper-system
      - istio-system
      - cattle-istio-system
      - cattle-logging-system
      - cattle-windows-gmsa-system
      - cattle-sriov-system
      - cattle-ui-plugin-system
      - tigera-operator
    kind: PodSecurityConfiguration
  name: PodSecurity
  path: ""
```

**Comment by snasovich** [comment]
@btat @martyav , just highlighting this as something we want to have done for 2.7.2 so assigned to you for visibilty.

**Comment by martyav** [comment]
@snasovich @btat  I'll take this one. Just opened a draft PR at #498.
