### ISSUE TITLE
[2.7.2 K8s 1.25] Instructions for using helm-mapkubeapis plugin  

### ISSUE THREAD

**Issue by prachidamle** [rancher/rancher-docs#488]
**Summary:**
We need to add instructions about how to use the helm-mapkubeapis plugin  for a Kubernetes cluster that has upgraded to k8s 1.25 but has some deprecated PSP resources present in the cluster.

**Comment by prachidamle** [comment]
@btat We are going to document about "how to use the helm-mapkubeapis plugin" for k8s 1.25 clusters stuck with deprecated psp related resources. @stormqueen1990 will be adding the docs, can you please point her to where these docs should go?

**Comment by btat** [comment]
@stormqueen1990 We're currently using the `release/v2.7.2` branch for 2.7.2 docs. 

We've been using the https://github.com/rancher/rancher-docs/tree/release/v2.7.2/docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration directory as the starting point to hold content for PSP/PSS/PSA.

Depending on the content for this issue, it could possibly be a subsection within https://github.com/rancher/rancher-docs/blob/release/v2.7.2/docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/create-pod-security-policies.md though.

**Comment by stormqueen1990** [comment]
Hi there, @btat! 👋

Gotcha! I'll take a look at those docs to see where this part would fit better. Thanks!
