### ISSUE TITLE
[Rancher2] Document updated migration process from V1 to V2

### ISSUE THREAD

**Issue by jtravee** [rancher/rancher-docs#49]
- [ ] Update [Migration steps from Monitoring V1 to V2](https://rancher.com/docs/rancher/v2.6/en/monitoring-alerting/guides/migrating/#migrating-from-monitoring-v1-to-monitoring-v2)
- [ ] Update release notes with the above updates, link to docs.

Estimated milestone is 2.7.1.

**Comment by btat** [comment]
Closing this V2 has been around since 2.5 and we're at 2.7 (soon to be 2.8) now and we don't have specifics around what needs to be updated.
