### ISSUE TITLE
Update RKE hardening guide for cis-benchmark

### ISSUE THREAD

**Issue by doflamingo721** [rancher/rancher-docs#495]
**Summary:**
- To install rancher-cis benchmark chart on a hardened 1.23 and 1.24 cluster we need to set the `global.psp.enabled=true` in the values for rancher-cis-benchmark chart version 4.0.0 and above before the installation.
- The reason for this is the RKE hardened cluster has restricted PSP applied as part of hardening and the cis-benchmark chart 4.0.0 has PSPs [disabled](https://github.com/rancher/charts/blob/8c110be844b640a5d7f823e4c12f2ba05167d9a2/charts/rancher-cis-benchmark/4.0.0-rc3/values.yaml#L47) by default. This causes the chart installation to fail on a hardened cluster since the chart PSPs are disabled. 
- We need to update the hardening guide with this additional step that when a cluster is being hardened, the values for cis-benchmark chart 4.0.0 and up should be updated by setting `global.psp.enabled=true`  - this would ensure that with PSP's are enabled, so the chart installation and scans will succeed.

**Linked issue:**
https://github.com/rancher/rancher/issues/40820

**Comment by doflamingo721** [comment]
@btat Can you please suggest where this update should go? I believe it should be a part of rke [hardening guide ](https://github.com/rancher/rancher-docs/blob/main/docs/security/hardening-guides/rke-1.6-hardening-2.6/Rancher_v2-6_CIS_v1-6_Hardening_Guide.pdf). If not can you please point us to the correct document.

**Comment by prachidamle** [comment]
@btat If that is the correct location for the content can a PR be raised to add it in?

**Comment by btat** [comment]
@doflamingo721 @prachidamle Since this is about setting a Helm value when installing the chart, [this page](https://github.com/rancher/rancher-docs/blob/release/v2.7.2/docs/how-to-guides/advanced-user-guides/cis-scan-guides/install-rancher-cis-benchmark.md) is on installing the CIS benchmark chart may be a better location. 

Just to confirm, is the cis-benchmark chart 4.0.0 targeted for 2.7.2 and will it be applicable to 2.6 as well?

**Comment by doflamingo721** [comment]
@btat cis-benchmark 4.0.0 is targeted for 2.7.2 and the same won't be applicable for 2.6.

**Comment by btat** [comment]
Closed via #503
