### ISSUE TITLE
Cannot retrieve bootstrap password on first login to webgui

### ISSUE THREAD

**Issue by jakeconnolly** [rancher/rancher-docs#523]
I'm very new to this. 

I'm running:
ubuntu 22.04.2
docker 20.10.21

I installed rancher using the following command:
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  -v /opt/rancher:/var/lib/rancher \
  --privileged \
  rancher/rancher:latest

I can reach the prompt on the web gui asking me to run: 
docker logs  container-id  2>&1 | grep "Bootstrap Password:"
to get my temporary password. When i run this command after getting the container ID using docker ps, the command returns nothing. 
I have also tried setting the password by adding: 
  -e CATTLE_BOOTSTRAP_PASSWORD=password\
to the docker run command, this did not work.

Thank you for the help.

**Comment by martyav** [comment]
@jakeconnolly you should also open an issue with https://github.com/rancher/rancher/issues. You're more likely to get help from the community there. We're focused on Rancher documentation and would need to reach out to an SME.
