### ISSUE TITLE
GitRepo status fleet

### ISSUE THREAD

**Issue by mrolmedo** [rancher/rancher-docs#538]
Hi there,
Our documentation includes the different statuses regarding bundles and clusters fleet objects:
- Latest version: https://fleet.rancher.io/cluster-bundles-state
- 0.5 version: https://fleet.rancher.io/0.5/cluster-bundles-state
- 0.4 version: https://fleet.rancher.io/0.4/cluster-bundles-state

Could we include or add the same kinf of information for GitRepo objects?

Thanks

**Comment by martyav** [comment]
@mrolmedo Would this be for the Rancher Manager docs, or the Fleet docs?

**Comment by mrolmedo** [comment]
Hi @martyav, Fleet docs.

**Comment by martyav** [comment]
Hi, @mrolmedo. Closing this issue after creating an issue on the fleet-docs repo, so they've been made aware.
