### ISSUE TITLE
Cilium RKE2 BGP features

### ISSUE THREAD

**Issue by mrolmedo** [rancher/rancher-docs#539]
Per our documentation, we do support Cilium and [eBPF feature] (https://docs.rke2.io/install/network_options), "```Cilium includes advanced features to fully replace kube-proxy and implement the routing of services using eBPF```
The Engineering team, SURE-6137, confirmed me that we also support BGP and BGP control plane features.
Could that be included or mentioned in that section of the docs?

Thanks

**Comment by martyav** [comment]
This seems like a likely place to add that content: https://ranchermanager.docs.rancher.com/faq/container-network-interface-providers

I'll see if there are other pages...

**Comment by mrolmedo** [comment]
Hi @martyav I think this can be closed. I reread our documentation, https://docs.rke2.io/install/network_options, the line `For more information about values available in the Cilium chart, please refer to the [rke2-charts repository](https://github.com/rancher/rke2-charts/blob/main/charts/rke2-cilium/rke2-cilium/1.12.301/values.yaml)` it is not self explanatory, but, if you check the charts you could find what features are shipped.

**Comment by mrolmedo** [comment]
Thanks for your attention

**Comment by mrolmedo** [comment]
The shipped or supported features can be infer from the charts.
