### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by btat** [rancher/rancher-docs#583]
~~This is a placeholder for when the Product/Engineering teams indicate that the API is ready to be documented, at which point specifics can be added.~~

These are the subtasks currently targeted for the initial iteration:

- [x] #857
- [x] #920
- [x] #996

**Comment by stefanlasiewski** [comment]
We are an enterprise customer. API documentation would help us with some of our tools that interface with Rancher & the API. We have have occasionally been hindered at the lack of documentation and mystery of certain Rancher behaviors.

**Comment by martyav** [comment]
Add a API quickstart page under the (to be added) API section, SURE-6847

**Comment by btat** [comment]
Hi @stefanlasiewski, the Swagger component is under the v2.8 (preview) docs set at https://ranchermanager.docs.rancher.com/v2.8/api/api-reference. Once v2.8 is released, it'll be mirrored to the latest docs set as well.
