### ISSUE TITLE
Add password requirements

### ISSUE THREAD

**Issue by btat** [rancher/rancher-docs#593]
Creating this issue as an extension of https://github.com/rancher/rancher-docs/pull/588.

The password requirements are provider agnostic so a better solution is to list out the password requirements in a central area and link to it rather than repeating them on each provider's page.

Possible pages affected:
- https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/bootstrap-password

Related:
- https://github.com/rancher/rancher-docs/pull/592

**Comment by martyav** [comment]
Some relevant PRs

---

## Parent issue

- https://github.com/rancher/dashboard/issues/6633
---

## Pull requests

- https://github.com/rancher/dashboard/pull/6801 - v2.6.9:
  - Added new setting inside "Global Setting" using key password-min-length.
- https://github.com/rancher/dashboard/pull/6897 - v2.7.2:
  - Prevent users to submit password configuration which is not matching the requirement: min 2 and max 256 chars. 
- https://github.com/rancher/dashboard/pull/7930 - v2.7.2: 
  - Added validation for integers exclusively for min-password changes
  - Changed setting key CATTLE_PASSWORD_MIN_LENGTH to PASSWORD_MIN_LENGTH, to match server returned value
  - Allowed editing settings from environment variables; this is due server configuration have been changed for this case
  - Updated tests - https://github.com/rancher/dashboard/pull/7930/commits/3d5a9810e7dfc2e115e38072f0e045ff3d60bf77
- https://github.com/rancher/dashboard/pull/8006 - v2.7.2
  - New case with decimal using 0 as value, e.g. 1.0.
