### ISSUE TITLE
Configuration of the Cluster Agent and Fleet Agent for scheduling and resource/limits

### ISSUE THREAD

**Issue by deniseschannon** [rancher/rancher-docs#600]
**Summary:**
Since cluster and fleet agents are deployed by Rancher, we're exposing ability to schedule these pods as well adding requests and limits to the pods during cluster provisioning for RKE1, RKE2/k3s and EKS clusters.

**Details:**
In the design doc, you can find a link to the PDO as well as the UI designs. 
Design Docs: https://confluence.suse.com/pages/viewpage.action?pageId=1185186511

This feature will be landing in the Q2 2023 release. 

Related issue: https://github.com/rancher/rancher/issues/41035

**Comment by aalves08** [comment]
Screenshots for the Agent Configuration RKE2 side:

![Screenshot 2023-05-11 at 10 21 08](https://github.com/rancher/rancher-docs/assets/97888974/00986eb2-211e-4335-abf8-bf331bf86371)
![Screenshot 2023-05-11 at 10 21 28](https://github.com/rancher/rancher-docs/assets/97888974/856289b7-16aa-4830-8e50-13ebfb39cfe0)
![Screenshot 2023-05-11 at 10 21 34](https://github.com/rancher/rancher-docs/assets/97888974/41b10682-18f9-4100-95da-dc939ffb2f72)
![Screenshot 2023-05-11 at 10 21 41](https://github.com/rancher/rancher-docs/assets/97888974/704d2ad0-b63d-479a-b56d-7c78680e7ae1)
![Screenshot 2023-05-11 at 10 21 46](https://github.com/rancher/rancher-docs/assets/97888974/307f26d6-ea0e-4292-be7b-164f6fbd4e44)

Does that work @deniseschannon or do you need something more particular?

**Comment by mantis-toboggan-md** [comment]
RKE1:
![Screen Shot 2023-05-11 at 11 08 38 AM](https://github.com/rancher/rancher-docs/assets/42977925/b22a26f7-4d38-4a8d-a29f-69069efd88ee)

EKS:
![Screen Shot 2023-05-11 at 11 08 13 AM](https://github.com/rancher/rancher-docs/assets/42977925/961cd0e2-e059-4d73-a213-5b59d18202d4)

The following are the same for RKE1 and EKS:
![Screen Shot 2023-05-11 at 11 06 35 AM](https://github.com/rancher/rancher-docs/assets/42977925/569058c2-108e-4881-97ef-6e71ad96f1b0)
![Screen Shot 2023-05-11 at 11 06 46 AM](https://github.com/rancher/rancher-docs/assets/42977925/35d11141-75fe-48db-a674-a435cbdba5b0)
![Screen Shot 2023-05-11 at 11 07 00 AM](https://github.com/rancher/rancher-docs/assets/42977925/b25de931-c8b5-48be-93c8-36c7ff5222d6)

**Comment by deniseschannon** [comment]
It'll be up to @btat if the docs team needs more info. @btat let me know if you need more context in anything but hoping the design docs give your team enough context to write docs

**Comment by snasovich** [comment]
Please note that as part of this feature 2 new settings were added to Rancher to hold default affinity for `cattle-cluster-agent` and `fleet-agent` respectively: `cluster-agent-default-affinity` and `fleet-agent-default-affinity`.
We want to discourage the users from changing these as there may be unwanted side effects if these settings are changed when there are existing downstream clusters. Also, if users override the values of these settings, if the default value changes in newer version of Rancher their overridden value will continue taking precedence.

This noted, when documenting these settings please add a note that updating the values of these settings is not officially supported and may lead to unwanted side effects for existing downstream clusters.

FYI @btat

**Comment by martyav** [comment]
@deniseschannon are there minimum values we need to document?

From Confluence: 
> If minimum values for the agents are known those values will be documented.
