### ISSUE TITLE
Document "Truncate hostnames to 15 characters for NetBIOS compatibility" checkbox

### ISSUE THREAD

**Issue by snasovich** [rancher/rancher-docs#607]
**Summary:**
Per https://github.com/rancher/dashboard/issues/8223 new "Truncate hostnames to 15 characters for NetBIOS compatibility" checkbox was added to Create / Edit Cluster form's "Networking" tab for node-provisioned RKE2/k3s clusters.
Related backend issue: https://github.com/rancher/rancher/issues/40901

**Details:**
Refer to the linked UI ticket for more information. However, it's important to document that this option can only be selected at cluster creation, and on Edit Cluster it simply shows whether it was selected or not.

This feature will be landing in the Q2 2023 release.

**Comment by snasovich** [comment]
@btat , please let us know if you need more info on this feature.
For screenshots and any UI-related questions suggesting to contact @bisht-richa who implemented the feature on UI side cc: @nwmac @gaktive 
FYI: @Sahota1225 @sowmyav27 @daviswill2

**Comment by martyav** [comment]
I've started drafting the PR at https://github.com/rancher/rancher-docs/pull/664

@snasovich could you/the team provide a description of how to manually set the hostname limit to something less than 15 characters? From what I read it seems like this is something that can only be done manually, not through the UI, so we should specify the field and maybe provide an example users can copy/paste.

**Comment by snasovich** [comment]
@martyav , thank you for starting on this.
I'd say for this feature we want to deliberately limit public-facing documentation to what UI allows as we've built a bit more flexibility on the back-end for "future use cases" and the testing of capabilities beyond what UI provides was limited.
FYI @jakefhyde

**Comment by btat** [comment]
Closed by https://github.com/rancher/rancher-docs/pull/706.
