### ISSUE TITLE
Hardware Requirements for RKE2 Kubernetes

### ISSUE THREAD

**Issue by masap** [rancher/rancher-docs#615]
**Summary:**
One customer asked whether RKE2 could be used in large clusters after reading the following document.

https://ranchermanager.docs.rancher.com/pages-for-subheaders/installation-requirements#rke2-kubernetes

I am told that RKE2 clusters are also used in large clusters by some customers. Therefore, could you please add a table for RKE2 with Deployment Size larger than `large`?

**Comment by btat** [comment]
Addressed by https://github.com/rancher/rancher-docs/pull/896.
