### ISSUE TITLE
Specify that Rancher does not support importing GKE autopilot cluster

### ISSUE THREAD

**Issue by cpinjani** [rancher/rancher-docs#631]
Follow on from: https://github.com/rancher/rancher/issues/41654

Please update this page: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters

To clarify that we do not support importing GKE autopilot cluster.
FYI, we already specify this for provisioning new cluster [here](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/gke#2-create-the-gke-cluster), information needs to be added for importing cluster.

**Comment by martyav** [comment]
@cpinjani While working on this, I noticed something. The 2.7.x page specifies, "To successfully import them into or provision them from Rancher, Elastic Kubernetes Service (EKS), Azure Kubernetes Service (AKS), and Google Kubernetes Engine (GKE) clusters must have at least one managed node group." This is also true for 2.6 and 2.5, right? Currently, those pages only state, "EKS clusters must have at least one managed node group to be imported into Rancher or provisioned from Rancher successfully." -- no mention of AKS or GKE. If that needs correcting, I'll make the edit in the same pull request.

**Comment by cpinjani** [comment]
Adding @rancher/highlander to confirm on the above query.
