### ISSUE TITLE
Update RKE2 documentation about Windows

### ISSUE THREAD

**Issue by vincebrannon** [rancher/rancher-docs#660]
**Summary:**
https://docs.rke2.io/install/quickstart#windows-agent-worker-node-installation

Is still referring to this feature being experimental and is referencing a old version of RKE2:

_Windows Support is currently Experimental as of v1.21.3+rke2r1 Windows Support requires choosing Calico as the CNI for the RKE2 cluster_

We need to review this section and al least update the versions mentioned to keep it up-to-date.

**Comment by martyav** [comment]
This repo doesn't contain that page. 

I just opened an issue over on the RKE2 docs repo: https://github.com/rancher/rke2/issues/4311
