### ISSUE TITLE
[BUG] Hyperlink broken for Private GKE cluster creation details

### ISSUE THREAD

**Issue by cpinjani** [rancher/rancher-docs#662]
**Rancher Server Setup**
Rancher version: 2.7.5-rc1
Installation option: Helm Chart
If Helm Chart, Kubernetes Cluster and version: GKE with Kubernetes 1.26.3-gke.1000

**Information about the Cluster**
Kubernetes version: GKE with Kubernetes 1.26.3-gke.1000
Cluster Type (Downstream): Hosted = GKE

**User Information**
What is the role of the user logged in? - Cluster Owner

**Describe the bug**
Creation of node pools with same name must be handled gracefully. While provisioning new GKE cluster, it starts provisioning and fails. While editing existing cluster, it starts updating and fails. Both scenarios should be restricted for user to perform.

**To Reproduce**
1. Add valid GCP cloud credentials
2. Provision downstream GKE cluster with private option, click on link on the page [GKE cluster provisioning docs](https://rancher.com/docs/rancher/v2.7/en/cluster-provisioning/hosted-kubernetes-clusters/gke/)
It navigates to https://rancher.com/docs/rancher/v2.7/en/cluster-provisioning/hosted-kubernetes-clusters/gke/

**Result**
Hyperlink broken for Private GKE cluster creation details

**Expected Result**
Hyperlink should be updated for Private GKE cluster creation details

**Screenshot**
![image](https://github.com/rancher/gke-operator/assets/73099870/d31db399-2719-47de-bbba-da1531efc6db)

**Comment by gaktive** [comment]
Some connection to https://github.com/rancher/rancher-docs/issues/663
