### ISSUE TITLE
[BUG] Hyperlink broken for Private AKS cluster creation details

### ISSUE THREAD

**Issue by salasberryfin** [rancher/rancher-docs#663]
**Rancher Server Setup**
- Rancher version: [2.7.5-rc1](https://github.com/rancher/rancher/releases/tag/v2.7.5-rc1)
- Installation option: **Helm**
   - If Helm Chart, Kubernetes Cluster and version: **AKS with Kubernetes v1.25.5**

**Information about the Cluster**
- Kubernetes version: **v1.26.0**
- Cluster Type: **AKS cluster**

**User Information**
- What is the role of the user logged in? **Admin**

**Describe the bug**
This issue was found during [validation of version 2.7.5-rc1](https://github.com/rancher/rancher/issues/41541).

When provisioning a private AKS cluster (selecting the 'Enable Private Cluster' option), a pop-up appears with the following message:

```text
AKS private clusters is an advanced use case which requires Rancher to be running on the same NAT as the AKS 
nodes. Before enabling private clusters ensure you have read through the AKS cluster provisioning docs for 
instructions on configuring AKS so nodes may communicate with Rancher.
```

Including the link [AKS cluster provisioning docs](https://rancher.com/docs/rancher/v2.7/en/cluster-provisioning/hosted-kubernetes-clusters/aks/), which returns a 404 error.

**To Reproduce**
- Using Rancher UI, provision a new AKS cluster
- Configure the cluster to be private: Networking Options -> Show advanced options -> Enable Private Cluster

**Result**
Link to documentation [AKS cluster provisioning docs](https://rancher.com/docs/rancher/v2.7/en/cluster-provisioning/hosted-kubernetes-clusters/aks/) returns `404 - Not found`

**Expected Result**
Hyperlink should be updated for Private AKS cluster creation details

**Screenshots**
![image](https://github.com/rancher/aks-operator/assets/10220061/8571b733-bccb-4607-9c3c-9321de32af3a)

**Additional context**
This issue has also been identified for other providers:
- rancher/rancher-docs#662

**Comment by btat** [comment]
Redirects have been added.

@nwmac @gaktive we now have a versioned link for all docs so hopefully that makes things easier for the UI team.
