### ISSUE TITLE
We have a new flag change while using GKE ingress, update the rancher installation on the GKE clusters 

### ISSUE THREAD

**Issue by anupama2501** [rancher/rancher-docs#669]
**Summary:**
Please add additional info in the following page:
https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-gke 

To successfully install Rancher on GKE clusters using a GKE ingress, it is necessary to include the following flag in the installation command: --set service.type: NodePort

Reference issue: https://github.com/rancher/rancher/issues/16061

**Comment by martyav** [comment]
@anupama2501 @btat I can take this one
