### ISSUE TITLE
[Rancher2] Discourage Docker installs, reduce friction for Helm CLI installs

### ISSUE THREAD

**Issue by catherineluse** [rancher/rancher-docs#68]
The Docker install creates a lot of bugs and a bad user experience when users try to use it in production. The quickstart guides should start people off with a single-node K3s install instead of a single-node Docker install so that new Rancher users can start out on the right foot. @nikkelma may be able to help with this.

**Comment by martyav** [comment]
Since https://github.com/rancher/docs/pull/3934 is merged, I think it's fair to close this
