### ISSUE TITLE
Documentation for the improved Install Process for Kubernetes v1.25 and Above

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher-docs#708]
This is related to https://github.com/rancher/rancher/issues/41455

## What's changed:
- Rancher versions 2.7.2 and above required users to set `global.cattle.psp.enabled` to `false` to properly install on Kubernetes versions 1.25 and above. Rancher will now attempt to detect if a cluster is running a Kubernetes version where PSPs are not supported, and will default it's usage of PSPs to false if it can determine that PSPs are not supported in the cluster. Users can still manually override this by explicitly providing `true` or `false` for this value. Rancher will still use PSPs by default in clusters which support PSPs (such as clusters running Kubernetes versions 1.24 or lower).
- If users have installed Rancher with PSPs enabled on a cluster which does not support PSPs (generally by overriding this value to `true` when installing the chart), you may experience issues when attempting to uninstall Rancher, which can leave resources behind. In these cases, users should use the [Rancher cleanup tool](https://github.com/rancher/rancher-cleanup) to remove any left-over artifacts of Rancher, and complete the uninstall process. See [#41455](https://github.com/rancher/rancher/issues/41455) for more details.

## Documentation change:
The [install](https://ranchermanager.docs.rancher.com/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster) and [upgrade](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades) documentation for Rancher needs to be updated to reflect the improved install process for K8s v1.25 and above since providing the cattle.global.psp.enabled flag is no longer mandatory.

Cc @MbolotSuse

**Comment by btat** [comment]
Closed by #710
