### ISSUE TITLE
[META] Convert Rancher docs to Docusaurus

### ISSUE THREAD

**Issue by sirredbeard** [rancher/rancher-docs#72]
- [x] Rancher Desktop
- [x] Harvester
- [x] Fleet
- [x] Epinio
- [x] Kubewarden
- [x] Elemental
- [x] Opni
- [x] ~Hypper~ No migration needed
- [ ] NeuVector
- [x] RKE2
- [x] k3s
- [x] Rancher - See [this comment](https://github.com/rancher/rancher-docs/issues/72) for details

References:
- https://docusaurus.io/
- https://github.com/rancher-sandbox/docs.rancherdesktop.io

**Comment by pgonin** [comment]
I don't believe it's needed to migrate hypper doc to docusaurus. Can we keep it as it is ?

**Comment by btat** [comment]
> I don't believe it's needed to migrate hypper doc to docusaurus. Can we keep it as it is ?

^ @gunamata

**Comment by gunamata** [comment]
yeah, let's keep hypper as-is

**Comment by btat** [comment]
Closing to only have issues related to RM on this repo.
