### ISSUE TITLE
Review UI Getting Started page for docs material

### ISSUE THREAD

**Issue by btat** [rancher/rancher-docs#726]
Ref: https://github.com/rancher/dashboard/issues/7413

The dashboard team is in the process of removing written material, e.g. release notes and a getting started page, that's bundled in the UI. For this ticket, the docs team should review https://github.com/rancher/dashboard/blob/master/shell/content/docs/en-us/getting-started.md for any new information that can be added to the docs.

**Comment by martyav** [comment]
I did an inventory of the items listed in the "Migrating from Cluster Manager" table last night. About half of the listed items have corresponding pages that contain instructions for how to find them in the Rancher UI. Others only seem to have CLI commands included in our docs, or are so frequently navigated to (the clusters list) that there's no particular page to link users to. 

Feature | Page | Note
-|-|-
Cluster drivers | https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-cluster-drivers#docusaurus_skipToContent_fallback | /
RKE (Cluster) Templates | https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-rke1-templates/manage-rke1-templates | /
RKE Cloud Credentials | https://ranchermanager.docs.rancher.com/reference-guides/user-settings/manage-cloud-credentials | The instructions on this page aren't RKE1-specific. The original table indicates that this feature can be found under **RKE1 Configuration** but I don't see that listed in 2.7. The 2.6 version of the page also lists the alternate, non-RKE1 path. I think the table might be outdated
RKE Node Templates | https://ranchermanager.docs.rancher.com/reference-guides/user-settings/manage-node-templates | /
Pod Security Policy | https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/manage-projects/manage-pod-security-policies#docusaurus_skipToContent_fallback | /
Cluster (functionality) | https://ranchermanager.docs.rancher.com/pages-for-subheaders/access-clusters | This page doesn't really describe how to navigate to the feature but it contains a subheading that would be a natural place to correct that
Projects/Namespaces | https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/projects-and-namespaces#docusaurus_skipToContent_fallback | /
Namespaces | https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/projects-and-namespaces#docusaurus_skipToContent_fallback
Alerts | https://ranchermanager.docs.rancher.com/reference-guides/monitoring-v2-configuration/receivers | This isn't along the legacy path suggested by the original table
Monitoring |  https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/monitoring-alerting-guides/enable-monitoring#docusaurus_skipToContent_fallback | /
CLI Download | https://ranchermanager.docs.rancher.com/reference-guides/cli-with-rancher/rancher-cli#download-rancher-cli | /
API and Keys | https://ranchermanager.docs.rancher.com/reference-guides/user-settings/api-keys#api-keys-and-user-authentication | /
Preferences | https://ranchermanager.docs.rancher.com/reference-guides/user-settings/user-preferences#docusaurus_skipToContent_fallback

**Comment by martyav** [comment]
@btat For the info regarding features that are now hidden by the **Legacy** feature flag in the UI -- should we add instructions to /docs, /2.7, /2.6, etc. on the relevant feature pages (Example for Alerts: "You can turn on v1 Alerts by <instructions>. Once you do that, you can find controls for them under <instructions>"), or simply point to the /versioned_docs pages where this information is already recorded ("V1 Alerts are considered a legacy feature. If you're looking for information, <link to page>")?

**Comment by btat** [comment]
> @btat For the info regarding features that are now hidden by the **Legacy** feature flag in the UI -- should we add instructions to /docs, /2.7, /2.6, etc. on the relevant feature pages (Example for Alerts: "You can turn on v1 Alerts by _instructions_. Once you do that, you can find controls for them under _instructions_"), or simply point to the /versioned_docs pages where this information is already recorded ("V1 Alerts are considered a legacy feature. If you're looking for information, _link to page_")?

I think option 2 is fine if the navigation/steps (after enabling the legacy feature) are the same on versions where it's considered legacy and versions where it's not (e.g. <=2.5).

**Comment by martyav** [comment]
- V1 (cluster) Alerts: https://ranchermanager.docs.rancher.com/v2.0-v2.4/pages-for-subheaders/cluster-alerts#adding-cluster-alerts
- V1 Notifiers: https://ranchermanager.docs.rancher.com/v2.0-v2.4/explanations/integrations-in-rancher/notifiers#adding-notifiers
- V1 (cluster) Monitoring: https://ranchermanager.docs.rancher.com/v2.0-v2.4/pages-for-subheaders/cluster-monitoring#enabling-cluster-monitoring
- V1 (cluster) Metrics: https://ranchermanager.docs.rancher.com/v2.0-v2.4/explanations/integrations-in-rancher/cluster-monitoring/cluster-metrics <-- need to add explicit UI instructions, buy already has instructions for other, more deeply nested, metrics
- V1 (node) Metrics: https://ranchermanager.docs.rancher.com/v2.0-v2.4/explanations/integrations-in-rancher/cluster-monitoring/cluster-metrics#finding-node-metrics
- V1 (workload) Metrics: https://ranchermanager.docs.rancher.com/v2.0-v2.4/explanations/integrations-in-rancher/cluster-monitoring/cluster-metrics#finding-workload-metrics
- V1 (pod) Metrics: Completely missing

**Comment by martyav** [comment]
Closing as review was performed for #739
