### ISSUE TITLE
Home: Docs: Error thrown when navigating to Docs page

### ISSUE THREAD

**Issue by yonasberhe23** [rancher/rancher-docs#727]
**Setup**
- Rancher version: v2.7.5
- Rancher UI Extensions: N/A
- Browser type & version: Any

**Describe the bug**
A console error is thrown when the user navigates to the Docs page. 

**To Reproduce**
- login to Rancher UI as an admin/standard user
- navigate to Home Page
- scroll down to support links
- click on 'Docs' link (https://ranchermanager.docs.rancher.com)
- open dev tools > console log
- note error in the console

**Result**
A console error is thrown when the user navigates to the Docs page. 

**Expected Result**
A console error should not be thrown when the user navigates to the Docs page. 

**Screenshots**

https://github.com/rancher/dashboard/assets/127343932/5f2c1861-8e01-4fb2-8260-e9c22dfa094d

**Comment by btat** [comment]
Initial poking around shows the `Uncaught ReferenceError: MktoForms2 is not defined` error is coming from either the [Docusaurus GTM plugin](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-tag-manager) we use or from our Google Tag Manager configuration managed by the Web team.

Web team has confirmed it's the latter and has taken action:

> It seems that the error you were getting was caused by Custom HTML "Marketo Form Submit". I have paused it under Rancher GTM.

I've tested with Chrome and Firefox and don't see that error anymore.
