### ISSUE TITLE
ADD: Transition to Get Started Cards

### ISSUE THREAD

**Issue by Deveesh-Shetty** [rancher/rancher-docs#733]
**Is your feature request related to a problem? Please describe.**
It is associated with the UI of the website, "Get-Started" cards on hover. they directly jump with no transition

**Describe the solution you'd like**
Adding a transition so the jump is smooth
![image](https://github.com/rancher/dashboard/assets/89470104/bfbf4e88-d166-4e4f-bc7a-2eadf21b0716)

**Additional context**
I want to improve it. Please assign the issue to me :)

**Comment by btat** [comment]
Hi @Deveesh-Shetty, thank you for offering to help improve the transitions on the https://www.rancher.com/quick-start page. That page is not part of the documentation, but I've out to the team that maintains it for more information on how you can contribute.

**Comment by Deveesh-Shetty** [comment]
Oh, my bad... Yea sure will wait for your call

Thank you!!

**Comment by btat** [comment]
Hi @Deveesh-Shetty, sorry for the delayed response, the relevant parties were out of office. The team that works on that part of the site said they've added this to their backlog. Once again, thank you for offering to help.
