### ISSUE TITLE
Restructure pages related to deploying apps

### ISSUE THREAD

**Issue by martyav** [rancher/rancher-docs#734]
Re: https://github.com/rancher/rancher-docs/pull/714

The pages in this section of the docs repeat information that also appears under Fleet Gitops at Scale. This is bad for maintenance, as the pages might drift out of sync. We should pick one section or the other. 

The PR referenced above had nothing to do with restructuring. It simply uncovered the problem. In the thread, the proposed the following:

>- For v2.7:
>   - Remove the current [Deploying Applications index page](https://ranchermanager.docs.rancher.com/pages-for-subheaders/deploy-apps-across-clusters) and have the user see [fleet-git-ops-at-scale](https://ranchermanager.docs.rancher.com/pages-for-subheaders/fleet-gitops-at-scale) in that section, in addition to [fleet-git-ops-at-scale](https://ranchermanager.docs.rancher.com/pages-for-subheaders/fleet-gitops-at-scale)'s current location under Rancher Integrations. 
>    - Don't mention the multi-cluster feature as an option, it's been removed. Maybe add a note that it's available in earlier Rancher versions.
>   - Remove both of the current subpages under /deploy-apps, and redirect their paths to [fleet-git-ops-at-scale](https://ranchermanager.docs.rancher.com/pages-for-subheaders/fleet-gitops-at-scale).
>- For versioned_docs:
>    - v2.5 and v2.6 we can leave alone since it's still available in the product.
>    - Leave v2.0-2.4 alone. There's no confusion there.
>- Update the note on some pages, "As of Rancher v2.5, multi-cluster apps are deprecated. We now recommend using [Fleet](https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/new-user-guides/deploy-apps-across-clusters/fleet) for deploying apps across clusters," to point to [fleet-git-ops-at-scale](https://ranchermanager.docs.rancher.com/pages-for-subheaders/fleet-gitops-at-scale)

**Comment by richard-cox** [comment]
Would like to +1 the removal of multi-cluster-apps from docs. It was marked as deprecated in 2.5.0 and removed in 2.7.0 (at least in the UI)

https://github.com/rancher/rancher/releases/tag/v2.5.0 `Deprecated Features`
https://github.com/rancher/rancher/releases/tag/v2.7.0 `Removed Legacy Features`
