### ISSUE TITLE
Update Documentation to Reflect Support for cert-manager.io/v1

### ISSUE THREAD

**Issue by btat** [rancher/rancher-docs#742]
SURE-6657

> The documentation currently lists cert-manager 1.11 being the Rancher-supported version, which is EOL in August. We should update the documentation to reflect that Rancher supports v1, instead of a specific version. 
>
> Something along the lines of "Rancher is compatible with the API version [cert-manager.io/v1](http://cert-manager.io/v1) and has been last tested with cert-manager version 1.11.0"

**Comment by PennyScissors** [comment]
@btat please see comment [here](https://github.com/rancher/rancher/issues/43015#issuecomment-1751508241)

**Comment by prachidamle** [comment]
@btat Can you update the docs based on the validation done by @PennyScissor Also, do you need any other data to create the docs update PR?
