### ISSUE TITLE
Update Note for CIS Chart Installation on hardened cluster 

### ISSUE THREAD

**Issue by Priyashetty17** [rancher/rancher-docs#755]
**Summary:**
The note in the Rancher documentation [here](https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/cis-scan-guides/install-rancher-cis-benchmark) needs to be updated to explicitly specify that it pertains to PSP hardened clusters as it is not relevant to PSA hardened clusters (K8s version >= 1.25). It only applies to PSP hardened clusters (K8s version < 1.25):
`CIS Benchmark 4.0.0 and above have PSPs disabled by default. To install CIS Benchmark on a hardened cluster, set global.psp.enabled to true in the values before installing the chart.`

cc @btat

**Comment by btat** [comment]
Addressed by #791.
