### ISSUE TITLE
Document Method for Rancher Users to Migrate from AWS In-Tree to Out-of-Tree Cloud Provider

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher-docs#763]
SURE-6512

**Comment by gaktive** [comment]
UI working on parts of this in these tickets:
- ability to deploy AWS out-of-tree (external) provider: https://github.com/rancher/dashboard/issues/9110
- removing in-tree if k8s 1.27+ in use: https://github.com/rancher/dashboard/issues/9204

**Comment by gaktive** [comment]
For UI feature completeness, can we get a placeholder page URL ASAP? @btat who's the best person to provide that?

**Comment by gaktive** [comment]
cc @nwmac

**Comment by gunamata** [comment]
@martyav , Can you please take care of this in the absence of @btat this week?

**Comment by martyav** [comment]
@gaktive do you just need a URL or do you also need a live page for the user to click thru to? We can use https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/migrate-from-in-tree-to-out-of-tree-aws for now. 

https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/migrate-from-in-tree-to-out-of-tree already exists as a published page, but it's vSphere specific (for now).

**Comment by gaktive** [comment]
@martyav either is fine so the placeholder gives us something to work with. fyi @mantis-toboggan-md
