### ISSUE TITLE
Update documentation related to the rancher-alpha helm repository

### ISSUE THREAD

**Issue by diogoasouza** [rancher/rancher-docs#765]
**Summary:**
The rancher-alpha helm repository is not being updated with the latest versions of the rancher charts, but the [documentation](https://ranchermanager.docs.rancher.com/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster#1-add-the-helm-chart-repository:~:text=helm%20repo%20add%20rancher%2Dalpha%20https%3A//releases.rancher.com/server%2Dcharts/alpha) still mentions it in the latest version even though the latest available version there is 2.6.x

**Comment by btat** [comment]
Per recent communication, the alpha repo will likely see activity in the near future so it's still a valid use case to have in the docs.
