### ISSUE TITLE
Add steps to install Rancher Extensions in an air-gapped environment

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher-docs#773]
There is work in progress for SURE-6065 to provide a way to install Rancher Extensions in an air-gapped environment. The approach requires an additional step or two on top of the steps provided in [Air-Gapped Helm CLI Install](https://ranchermanager.docs.rancher.com/pages-for-subheaders/air-gapped-helm-cli-install) page. We should capture those steps to install extensions in this page. 

@jordojordo from the UI team should be able to help with the actual steps.

**Comment by martyav** [comment]
@gunamata Could you provide more context about where the additional step or two would go, in terms of pages? https://ranchermanager.docs.rancher.com/pages-for-subheaders/air-gapped-helm-cli-install has instructions across 4 pages and I'm not sure where the update should/would go

**Comment by gunamata** [comment]
My understanding is that the additional step(s) needs to be performed after the rancher installation. In that case, I think we can add the steps to [4. Install Rancher](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/install-rancher-ha) page itself. Let's wait for @jordojordo to provide the actual steps .

**Comment by jordojordo** [comment]
The steps for installing/importing the catalog image can be found in the [dashboard documentation](https://rancher.github.io/dashboard/extensions/advanced/air-gapped-environments#importing-the-extension-catalog-image) - The user will need to be provided with the relevant information regarding the location of the image on the registry where they have stored the rancher-images.

**Comment by gunamata** [comment]
Sounds good @martyav, Thank you.
