### ISSUE TITLE
[Placeholder] k8s 1.27 support 

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher-docs#777]
This ticket is a placeholder for k8s 1.27 support 

SURE-6348

**Comment by Sahota1225** [comment]
https://github.com/rancher/rancher/issues/41840

**Comment by martyav** [comment]
@Sahota1225 Do you have more insight on what documentation needs to be added for v2.8 regarding Kubernetes 1.27 support? Are we ready to start drafting?

**Comment by btat** [comment]
@Sahota1225 is there something specific that needs to be called out or just general awareness that K8s 1.27 will be supported?

**Comment by btat** [comment]
Closing since historically we haven't done general "K8s vX.Y support" call outs and it doesn't look like there's anything specific to call out here.
