### ISSUE TITLE
[2.9.0] Graceful Shutdown of vSphere VM

### ISSUE THREAD

**Issue by Sahota1225** [rancher/rancher-docs#778]
This is a placeholder to add the support for configuring the graceful shutdown of VMs for node-driver clusters in Rancher when vSphere is used as the infrastructure provider.

SURE-3285

**Comment by Sahota1225** [comment]
https://github.com/rancher/rancher/issues/42308

**Comment by martyav** [comment]
@jiaqiluo Could we partner on drafting the documentation for this?

**Comment by jiaqiluo** [comment]
@martyav, Sure, I am happy to do it. 
But FYI, the feature, especially the Dashboard UI, might be postponed to Q1 24. We will see what we can do when that decision is made.

**Comment by btat** [comment]
@jiaqiluo @slickwarren Is the goal to only document the UI approach (in which case this can be moved to the next release) or are we documenting the workaround referenced in the parent issue?

**Comment by jiaqiluo** [comment]
Hi @btat,  AFAIK, the goal is to document only the UI approach.

**Comment by martyav** [comment]
@jiaqiluo Hi again. Since v2.9.0 is now closer, I think we should start working on a draft.

**Comment by jiaqiluo** [comment]
Hi @martyav,  below is the information about the new field, I hope it is sufficient for you to write the draft. Let me know if there is anything else I can help. 

Name | Graceful Shutdown Timeout
-- | --
Description | The time in seconds to wait before forcing deleting VMs in the infrastructure. Zero means disable graceful shutdown.
Data Type | integer
Value Range | >= 0


### Position in UI

For the RKE1 node template,  the new option shows in the creating/editing page for the vSphere node template. 

![image](https://github.com/rancher/dashboard/assets/16691014/9a2c60ac-9a24-4c42-80e6-68d03c763c10)

For REK2/K3S clusters, the new option shows in the machine pool section on the cluster creation/editing page

![image](https://github.com/rancher/dashboard/assets/16691014/b52788e8-2f74-4772-8424-102447525f6b)

**Comment by martyav** [comment]
@jiaqiluo I looked at the original issue recently -- is this a new feature for 2.9, or has this already been backported to 2.8 (https://github.com/rancher/dashboard/issues/10495)?

**Comment by jiaqiluo** [comment]
@martyav,  the feature is supported in the backend since v2.8.0  based on [this comment](https://github.com/rancher/rancher/issues/42308#issuecomment-1765467400), and the support in the UI is added on v2.8.3 based on [this comment](https://github.com/rancher/dashboard/issues/10495#issuecomment-2000379115) and the milestone
