### ISSUE TITLE
Add page for un-migration

### ISSUE THREAD

**Issue by martyav** [rancher/rancher-docs#789]
v2.7.6 release notes comment with lengthy description of how to undo a migration: https://github.com/rancherlabs/release-notes/pull/318#discussion_r1296415266

These details need to be added to the docs before the release, and linked to in the RN at https://github.com/rancherlabs/release-notes/pull/318

**Comment by martyav** [comment]
This feels like it should have a title such as, "Undoing a GUID Active Directory Migration", somewhere in the vicinity of Authentication, Permissions and Global Configuration or Troubleshooting. Not quite sure how to organize this to get started. @btat

**Comment by martyav** [comment]
Also see the issues in https://github.com/rancher/rancher/issues?q=is%3Aissue+is%3Aopen+milestone%3Av2.7.6+label%3Ateam%2Farea3

We will also need pages to make the scripts available, or at least link to where they are going to be hosted...

**Comment by martyav** [comment]
The two issues related to the scripts:

1. https://github.com/rancher/rancher/issues/42162
1. https://github.com/rancher/rancher/issues/42163

**Comment by btat** [comment]
> This feels like it should have a title such as, "Undoing a GUID Active Directory Migration", somewhere in the vicinity of Authentication, Permissions and Global Configuration or Troubleshooting. Not quite sure how to organize this to get started. @btat

I think putting the actual page under Troubleshooting is fine. We also need to make visible callouts and link out to the page from the various Authentication section and in the Upgrade section.

**Comment by martyav** [comment]
@btat although the issues are open, https://github.com/rancher/rancher/pull/42325, which contains the script, was merged. One of the files in that PR is a README on using the script: https://github.com/nflynt/rancher/blob/809618bdf43aa6ca61cc0fc45daa7a1aa2a73e68/cleanup/ad-guid-README.md

**Comment by martyav** [comment]
@snasovich How can users access the script?

**Comment by snasovich** [comment]
> @snasovich How can users access the script?

@martyav , I think it's for something that @MKlimuszka / @prachidamle lead.

**Comment by btat** [comment]
> > @snasovich How can users access the script?
> 
> @martyav , I think it's for something that @MKlimuszka / @prachidamle lead.

I think it's at https://github.com/rancher/rancher/tree/release/v2.7.6/cleanup.

**Comment by btat** [comment]
Per discussion, users won't be performing this manually so there are no instructions to add.
