### ISSUE TITLE
Need clarification of dependencies for vSphere clusters

### ISSUE THREAD

**Issue by lindhe** [rancher/rancher-docs#841]
In the instructions for creating vSphere Virtual Machine Templates, there is a list of dependencies that "need to be installed on the template":

https://github.com/rancher/rancher-docs/blob/bcfd5b25aa8a74f6f719949393344f32e4c322e0/docs/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/use-new-nodes-in-an-infra-provider/vsphere/create-a-vm-template.md?plain=1#L24-L42

Some of these dependencies (e.g., `cloud-init` and `openssh-server`) are _obviously_ there in order for Rancher to be able to manage the nodes, which is exactly the list of dependencies I want to see here.

But there are also other dependencies that may be required, depending on the user's environment (for example `docker` which is required if the user wants to provision RKE1 nodes). First of all, I think that this should also be mentioned here so that users remember to include those dependencies too. Secondly, it would be great if the initial paragraph was clearer with the fact that the current list of dependencies is _only_ for Rancher's node management (not the Kubernetes distribution itself).

If we could clarify this, I think that would be great. 👍

**Comment by brandond** [comment]
I believe that the cluster provisioner should handle installing distribution-specific additional items. On RKE1, docker will be installed at that time; it doesn't need to be preloaded on the image. RKE2 and K3s are self-contained and don't require anything beyond what's listed here.

Are you seeing otherwise?

**Comment by lindhe** [comment]
Ok, great. I'm not seeing otherwise. If we could just clarify that "the cluster provisioner should handle installing distribution-specific additional items" and that the current list is the dependencies needed for the cluster provisioner to do its work, then I'm happy. :)

**Comment by gabrielaomoraes** [comment]
@lindhe would you like to open a PR for that? We'd be happy to help you through the process. Otherwise we'll put it in our backlog.

**Comment by lindhe** [comment]
Sure, I'll open a PR. 👍

**Comment by lindhe** [comment]
Sorry for the delay, I was particularly busy the past weeks. Have created a PR now.
