### ISSUE TITLE
Clarify what "integer length" means

### ISSUE THREAD

**Issue by lindhe** [rancher/rancher-docs#845]
I've never heard of integer length before. Does it mean something particular, or is it a typo and it should say "integer value"?

https://github.com/rancher/rancher-docs/blob/bcfd5b25aa8a74f6f719949393344f32e4c322e0/versioned_docs/version-2.7/how-to-guides/new-user-guides/helm-charts-in-rancher/create-apps.md?plain=1#L117-L118

**Comment by brandond** [comment]
If the variable type is `int`, this sets the min and max allowed integer values, similar to how min_length and max_length set the minimum and maximum string length for string type values. It should probably say "integer value" not "integer length".
