### ISSUE TITLE
[Rancher2] Document URL where CVE image scanning report can be accessed

### ISSUE THREAD

**Issue by catherineluse** [rancher/rancher-docs#91]
https://github.com/rancher/docs/pull/3364#issuecomment-872727524

**Comment by martyav** [comment]
@btat Since https://github.com/rancher/docs/pull/3473 was reverted, should this be closed?

https://github.com/rancherlabs/rancher-security/issues/962 is the current tracking issue, and it's still open.

**Comment by btat** [comment]
> @btat Since [rancher/docs#3473](https://github.com/rancher/docs/pull/3473) was reverted, should this be closed?
> 
> [rancherlabs/rancher-security#962](https://github.com/rancherlabs/rancher-security/issues/962) is the current tracking issue, and it's still open.

Yup, let's chose this.
