### ISSUE TITLE
Migration doc is in need of clarification

### ISSUE THREAD

**Issue by Tejeev** [rancher/rancher-docs#911]
## Summary
https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/migrate-rancher-to-new-cluster

- It seems the following line means to refer to `<2.x.x>` to mean a variable that can equal any rancher 2 minor and dot version.  If this is the case, then it should follow the same practice as other variables by stating the variable name, what values it can take, then providing the example with the variable in place of the value
```
Select and set CHART_VERSION variable with a 2.x.x rancher-backup release version:

helm search repo --versions rancher-charts/rancher-backup
CHART_VERSION=<2.x.x>
```

- in that same theme, the following doesn't actually say that the `$REGISTRY` variable should be replaced with their path to registry
```
For an air-gapped environment, use the Helm value below to pull the backup-restore-operator image from your private registry when installing the rancher-backup Helm chart.

--set image.repository $REGISTRY/rancher/backup-restore-operator
```

- There is no mention of redirecting DNS after the migration so that it points to the new cluster.  This should be the last step.

**Comment by martyav** [comment]
Since this issue was created, a related PR has altered the page.

https://github.com/rancher/rancher-docs/pull/1111 - Removed the `<2.x.x>` variable, updated the instructions to read:

> Set a CHART_VERSION variable, selecting a rancher-backup chart version compatible with your version of Rancher. See the [support matrix](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions), within the Rancher Apps / Cluster Tools section, to see which rancher-backup versions are supported:
>> `CHART_VERSION=<chart-version>`

**Comment by martyav** [comment]
@Tejeev how do you redirect DNS to the new cluster after you migrate, to complete the last step?
