### ISSUE TITLE
increasing the keyspace size in etcd

### ISSUE THREAD

**Issue by mrolmedo** [rancher/rancher-docs#912]
## Summary

In Rancher 2.5, we have the procedure to increase the keyspace size when we 
see the error **mvcc: database space exceeded errors**, in the etcd logs or Kubernetes API server logs, you should consider increasing the keyspace size, https://ranchermanager.docs.rancher.com/v2.5/getting-started/installation-and-upgrade/advanced-options/advanced-use-cases/tune-etcd-for-large-installs#example-this-snippet-of-the-rke-clusteryml-file-increases-the-keyspace-size-to-5gb.

This information is not present for Rancher 2.6.X or 2.7. We have https://ranchermanager.docs.rancher.com/troubleshooting/kubernetes-components/troubleshooting-etcd-nodes#etcd-space-errors, although it is not detailed how to increase it. Could be worth it to include it on this section?

**Comment by btat** [comment]
The 2.6 and newer docs were reorganized as part of https://github.com/rancher/rancher-docs/pull/234, but the reorganization was not been applied to the 2.5 and older docs sets. The quoted page is one of the affected pages and has been moved under `how-to-guides/advanced-user-guides/tune-etcd-for-large-installs`


- https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/tune-etcd-for-large-installs#example-this-snippet-of-the-rke-clusteryml-file-increases-the-keyspace-size-to-5gb
- https://ranchermanager.docs.rancher.com/v2.6/how-to-guides/advanced-user-guides/tune-etcd-for-large-installs#example-this-snippet-of-the-rke-clusteryml-file-increases-the-keyspace-size-to-5gb
