### ISSUE TITLE
Hetzner Cloud Quick Start Guide is not Arm64 compatible

### ISSUE THREAD

**Issue by nicokempe** [rancher/rancher-docs#970]
## Related Issues
- https://ranchermanager.docs.rancher.com/getting-started/quick-start-guides/deploy-rancher-manager/hetzner-cloud the Quick Start Guide does only work for x86 (Intel/AMD) architecture.

## Summary
The new standard for most users (myself and some colleagues included) is now the Arm64 architecture. An update would be extremely cool. I don't know if the basic functionality is even there, but it doesn't work with this description. If this is related to the missing functionality and not the outdated documentation I would just move my issue.

<img width="1207" alt="image" src="https://github.com/rancher/rancher-docs/assets/50241630/49182347-04f9-44e0-8144-fa87bd4bacf1">
<img width="1205" alt="image" src="https://github.com/rancher/rancher-docs/assets/50241630/dd73e717-e149-4a3b-940c-4a5978891f1b">

**Comment by btat** [comment]
Hi @nicokempe, running Rancher on [ARM64 is an experimental feature](https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/enable-experimental-features/rancher-on-arm64) and our team has indicated it is still in this state as of this moment.  

If this is a feature you'd like to see you can head to https://github.com/rancher/rancher to +1 existing issue(s) (or create a new request if there are no existing ones) asking for this which helps our team with prioritization.

**Comment by nicokempe** [comment]
Thank you @btat :)
