### ISSUE TITLE
Add Cloud Marketplace Integration - Azure Marketplace Integration

### ISSUE THREAD

**Issue by tlssuse** [rancher/rancher-docs#987]
## Summary
Now that Rancher Prime is available in the Microsoft Azure Marketplace, update the documentation to reflect this.

## Details
1. Update "This integration only supports AWS" to "This integration supports Amazon Web Services and Microsoft Azure." on https://ranchermanager.docs.rancher.com/pages-for-subheaders/cloud-marketplace
2. Add an equivalent for Azure of the subsection, https://ranchermanager.docs.rancher.com/pages-for-subheaders/aws-cloud-marketplace

**Comment by btat** [comment]
Possible duplicate of https://github.com/rancher/rancher-docs/issues/987. @LucasSaintarbor to confirm.

**Comment by tlssuse** [comment]
@btat & @LucasSaintarbor : This does indeed appear to be a duplicate of #917.  Thank you for identifying it.  Feel welcome to close this issue.

**Comment by btat** [comment]
Thank you for the confirmation.
