### ISSUE TITLE
Clarify support and stipulations for use of firewall in documentation

### ISSUE THREAD

**Issue by gunamata** [rancher/rancher-docs#999]
SURE-7077

**Comment by martyav** [comment]
> The Rancher docs currently recommend turning off firewalld, but also contain a page for how to open it up. https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/open-ports-with-firewalld
> We should clarify our stance on this to aid customer confusion.

> Request description:
> Revise documentation to state that there are complications when using firewall and CNIs. We cannot say that using firewall is entirely unsupported, but we should recommend against it. 

> Actual behavior:
> Stance is unclear on if firewall is supported without issues.

> Expected behavior:
> RKE2 page reflecting applicable information to the k3s page https://docs.k3s.io/advanced?_highlight=firewalld#red-hat-enterprise-linux–centos

> Clarification on the Rancher docs site that use of firewall with CNIs is not recommended
